import{deterministicDigest}from"@/domain/events";import type{WatchWindow}from"@/domain/forecast";
export const CATALYST_CLASSIFICATION_POLICY="catalyst-classification-policy-v1";
export type CatalystEventType="EARNINGS"|"GUIDANCE"|"CONTRACT_AWARD"|"CONTRACT_LOSS"|"REGULATORY_APPROVAL"|"REGULATORY_RESTRICTION"|"M&A"|"CAPITAL_RAISE"|"BUYBACK"|"DIVIDEND"|"PRODUCT_LAUNCH"|"PARTNERSHIP"|"MANAGEMENT_CHANGE"|"LEGAL"|"SECURITY_INCIDENT"|"POLITICAL_STATEMENT"|"MACRO_POLICY"|"TOKEN_LISTING"|"TOKEN_DELISTING"|"TOKENOMICS_CHANGE"|"UNKNOWN";
export type CatalystNovelty="NEW"|"FOLLOW_UP"|"REPEAT"|"CORRECTION"|"UNKNOWN";export type CatalystEventStatus="ANNOUNCED"|"CONFIRMED"|"COMPLETED"|"CANCELLED"|"RUMOR"|"UNKNOWN";export type CatalystMateriality="LOW"|"MEDIUM"|"HIGH"|"VERY_HIGH"|"UNKNOWN";
export interface ClassificationInput{headline:string;summary:string|null;articleRevision:number;sourceClassification:string;entityConfidence:number;informationCutoffAt:string;availableAt:string}
export interface CatalystFact{factType:string;value:string|number;unit:string|null;currency:string|null;sourceText:string}
const rules:Array<[CatalystEventType,RegExp[]]>=[["TOKEN_DELISTING",[/\bdelist(?:s|ed|ing)?\b/i]],["TOKEN_LISTING",[/\blist(?:s|ed|ing)?\b.{0,30}\btoken\b/i,/\btoken\b.{0,30}\blist(?:s|ed|ing)?\b/i]],["CONTRACT_LOSS",[/\blost contract\b/i,/\bcontract (?:terminated|cancelled)\b/i]],["CONTRACT_AWARD",[/\b(?:awarded|wins?|secures?)\b.{0,60}\bcontract\b/i,/\bcontract award\b/i]],["REGULATORY_APPROVAL",[/\b(?:regulator|fda|sec|commission).{0,40}\bapprov(?:al|es|ed)\b/i]],["REGULATORY_RESTRICTION",[/\b(?:regulator|fda|sec|commission).{0,40}\b(?:ban|restrict|block|reject|fine)/i]],["GUIDANCE",[/\bguidance\b/i,/\boutlook\b/i]],["EARNINGS",[/\bearnings\b/i,/\bquarterly results\b/i,/\beps\b/i]],["M&A",[/\b(?:merger|acquisition|acquire[sd]?|takeover)\b/i]],["CAPITAL_RAISE",[/\b(?:capital raise|public offering|private placement|share issuance)\b/i]],["BUYBACK",[/\b(?:buyback|share repurchase)\b/i]],["DIVIDEND",[/\bdividend\b/i]],["PRODUCT_LAUNCH",[/\b(?:launches|launched|unveils|releases)\b.{0,50}\b(?:product|platform|service|device|model)\b/i]],["PARTNERSHIP",[/\b(?:partnership|partners with|collaboration)\b/i]],["MANAGEMENT_CHANGE",[/\b(?:appoints|resigns|steps down|names)\b.{0,40}\b(?:ceo|cfo|chair|president|director)\b/i]],["SECURITY_INCIDENT",[/\b(?:cyberattack|data breach|security incident|hacked)\b/i]],["LEGAL",[/\b(?:lawsuit|litigation|court|settlement|indictment)\b/i]],["POLITICAL_STATEMENT",[/\b(?:president|prime minister|minister|senator|trump)\b.{0,60}\b(?:says|said|announces|statement)\b/i]],["MACRO_POLICY",[/\b(?:central bank|federal reserve|ecb|interest rate|monetary policy|tariff)\b/i]],["TOKENOMICS_CHANGE",[/\b(?:tokenomics|token burn|vesting|supply change)\b/i]]];
export function classifyCatalyst(input:ClassificationInput){if(input.availableAt>input.informationCutoffAt)throw new Error("Future news revision rejected");const text=`${input.headline}\n${input.summary??""}`,matched=rules.find(([,patterns])=>patterns.some(pattern=>pattern.test(text))),eventType=matched?.[0]??"UNKNOWN",status=statusOf(text),novelty: CatalystNovelty=input.articleRevision===1?"NEW":"CORRECTION",facts=extractFacts(text),classificationConfidence=eventType==="UNKNOWN"?0:Math.min(95,60+(matched?.[1].filter(pattern=>pattern.test(text)).length??0)*10+(input.sourceClassification==="OFFICIAL_SOURCE"?15:input.sourceClassification==="PRIMARY_MEDIA"?10:0)),watchWindows=watchPolicy(eventType),missingInputs=["COMPANY_SCALE_CONTEXT_MISSING"];
const output={policyVersion:CATALYST_CLASSIFICATION_POLICY,eventType,materiality:"UNKNOWN"as CatalystMateriality,novelty,status,entityConfidence:input.entityConfidence,classificationConfidence,facts,watchWindows,missingInputs,direction:"UNKNOWN"as const};return{...output,classificationHash:deterministicDigest(output)}}
function statusOf(text:string):CatalystEventStatus{if(/\b(?:rumor|reportedly|in talks|considering)\b/i.test(text))return"RUMOR";if(/\b(?:cancelled|canceled|withdrawn|terminated)\b/i.test(text))return"CANCELLED";if(/\b(?:completed|closed the acquisition|finalized)\b/i.test(text))return"COMPLETED";if(/\b(?:confirmed|confirms|approved|awarded|signed)\b/i.test(text))return"CONFIRMED";if(/\b(?:announces|announced|plans?|will launch|declares)\b/i.test(text))return"ANNOUNCED";return"UNKNOWN"}
function watchPolicy(type:CatalystEventType):WatchWindow[]{if(["EARNINGS","GUIDANCE","POLITICAL_STATEMENT","SECURITY_INCIDENT","TOKEN_LISTING","TOKEN_DELISTING"].includes(type))return["ULTRA_SHORT","SHORT"];if(["REGULATORY_APPROVAL","REGULATORY_RESTRICTION","M&A","MACRO_POLICY","LEGAL"].includes(type))return["SHORT","MEDIUM"];return["SHORT"]}
function extractFacts(text:string):CatalystFact[]{const facts:CatalystFact[]=[],money=/(?:(USD|EUR|SEK|GBP)|([$€£]))\s?([0-9]+(?:\.[0-9]+)?)\s?(billion|million|bn|m)?/gi;for(const match of text.matchAll(money)){const multiplier=/billion|bn/i.test(match[4]??"")?1e9:/million|m/i.test(match[4]??"")?1e6:1,currency=match[1]?.toUpperCase()??({"$":"USD","€":"EUR","£":"GBP"}[match[2]]??null);facts.push({factType:"MONETARY_VALUE",value:Number(match[3])*multiplier,unit:match[4]??null,currency,sourceText:match[0]})}const percent=/\b([0-9]+(?:\.[0-9]+)?)\s?%/g;for(const match of text.matchAll(percent))facts.push({factType:"PERCENTAGE",value:Number(match[1]),unit:"percent",currency:null,sourceText:match[0]});return facts}
