import{deterministicDigest}from"./events";
export const FORECAST_INFRA_VERSION="forecast-infrastructure-v1",CATALYST_POLICY_VERSION="catalyst-watch-policy-v1",OUTCOME_POLICY_VERSION="forecast-outcome-policy-v1";
export type ForecastHorizon="5m"|"30m"|"2h"|"24h";export type ForecastMethod="INSUFFICIENT_DATA"|"HISTORICAL_BASELINE"|"STATISTICAL_MODEL"|"AGENT_ENSEMBLE";export type CatalystState="DETECTED"|"DORMANT"|"WATCHING"|"WATCHING_UNVERIFIED"|"ACTIVATING"|"RESOLVED"|"EXPIRED";export type SourceClassification="OFFICIAL_SOURCE"|"PRIMARY_MEDIA"|"REPUTABLE_SECONDARY"|"SOCIAL_VERIFIED"|"SOCIAL_UNVERIFIED"|"UNKNOWN";export type WatchWindow="ULTRA_SHORT"|"SHORT"|"MEDIUM";
const transitions:Record<CatalystState,CatalystState[]>={DETECTED:["DORMANT","WATCHING","WATCHING_UNVERIFIED"],DORMANT:["WATCHING","ACTIVATING","EXPIRED"],WATCHING:["ACTIVATING","RESOLVED","EXPIRED"],WATCHING_UNVERIFIED:["WATCHING","EXPIRED"],ACTIVATING:["RESOLVED","EXPIRED"],RESOLVED:[],EXPIRED:[]};
export function canTransitionCatalyst(from:CatalystState,to:CatalystState){return transitions[from].includes(to)}
export function assertCatalystTransition(from:CatalystState,to:CatalystState){if(!canTransitionCatalyst(from,to))throw new Error(`Invalid catalyst transition: ${from} -> ${to}`)}
export function watchUntil(availableAt:string,window:WatchWindow){const ms={ULTRA_SHORT:6*3600000,SHORT:3*86400000,MEDIUM:28*86400000}[window];return new Date(Date.parse(availableAt)+ms).toISOString()}
export function horizonMs(h:ForecastHorizon){return{ "5m":300000,"30m":1800000,"2h":7200000,"24h":86400000}[h]}
export function forecastKey(input:{assetId:string;catalystId:string|null;horizon:ForecastHorizon;cutoff:string;version:string}){return deterministicDigest(input)}
export function outcomeMetrics(input:{expected:number|null;lower:number|null;upper:number|null;entry:number;exit:number;path:number[]}){const actual=(input.exit/input.entry-1)*100,expected=input.expected;return{actualReturn:actual,directionCorrect:expected===null?null:(expected>=0)===(actual>=0),absoluteError:expected===null?null:Math.abs(expected-actual),rangeHit:input.lower===null||input.upper===null?null:actual>=input.lower&&actual<=input.upper,maxFavorableExcursion:(Math.max(...input.path)/input.entry-1)*100,maxAdverseExcursion:(Math.min(...input.path)/input.entry-1)*100}}
