import { describe, expect, it, vi } from "vitest";
import { BirdeyeHistoricalLiquidityProvider } from "../src/services/liquidity/birdeye-liquidity-provider";
import { BirdeyeTokenRiskProvider } from "../src/services/token-risk/birdeye-token-risk-provider";
import { BirdeyeHistoricalPriceProvider } from "../src/services/crypto-market/birdeye-historical-provider";
describe("Birdeye evidence providers", () => {
  it("normalizes historical token liquidity and caches identical lookups", async () => { const fetcher = vi.fn(async (input: string | URL | Request) => { expect(new URL(String(input)).searchParams.get("resolution")).toBe("1m"); return new Response(JSON.stringify({ success: true, data: { items: [{ unix_time: 1767225600, total_liquidity_usd: 125000 }] } }), { status: 200 }); }); const provider = new BirdeyeHistoricalLiquidityProvider("key", fetcher); const request = { assetId: "asset", mintAddress: "mint", from: "2026-01-01T00:00:00Z", to: "2026-01-01T00:02:00Z", informationCutoffAt: "2026-01-02T00:00:00Z" }; const first = await provider.getHistoricalLiquidity(request); const second = await provider.getHistoricalLiquidity(request); expect(first[0]).toMatchObject({ liquidityUsd: 125000, poolAddress: null, quality: 90, effectiveAt: "2026-01-01T00:00:00.000Z", informationAvailableAt: "2026-01-01T00:01:00.000Z" }); expect(second).toEqual(first); expect(fetcher).toHaveBeenCalledTimes(1); });
  it("normalizes and caches point-in-time historical prices", async () => { const fetcher = vi.fn(async (input: string | URL | Request) => { const url = new URL(String(input)); expect(url.searchParams.get("unixtime")).toBe("1787047200"); return new Response(JSON.stringify({ success: true, data: { address: "mint", updateUnixTime: 1787047200, value: 42.5 } }), { status: 200 }); }); const provider = new BirdeyeHistoricalPriceProvider("key", fetcher); const request = { mintAddress: "mint", timestamp: "2026-08-18T10:00:00.000Z" }; const first = await provider.getHistorical(request); const second = await provider.getHistorical(request); expect(first).toMatchObject({ mintAddress: "mint", priceUsd: 42.5, providerTimestamp: "2026-08-18T10:00:00.000Z", confidence: 95, completeness: "partial" }); expect(second).toEqual(first); expect(fetcher).toHaveBeenCalledTimes(1); });
  it("keeps missing historical prices explicitly unavailable", async () => { const fetcher = vi.fn(async () => new Response(JSON.stringify({ success: true, data: { address: "mint", updateUnixTime: 1787047200, value: null } }), { status: 200 })); const result = await new BirdeyeHistoricalPriceProvider("key", fetcher).getHistorical({ mintAddress: "mint", timestamp: "2026-08-18T10:00:00.000Z" }); expect(result).toMatchObject({ priceUsd: null, confidence: 0, completeness: "unavailable" }); });
  it("creates inspectable risk components without backdating them", async () => { const fetcher = vi.fn(async () => new Response(JSON.stringify({ success: true, data: { ownerAddress: null, freezeAuthority: null, freezeable: false, mutableMetadata: false, top10HolderPercent: 20, honeypot: false, isScam: false, nonTransferable: false, creatorAddress: "creator" } }), { status: 200 })); const before = new Date().toISOString(); const result = await new BirdeyeTokenRiskProvider("key", fetcher).assess("mint", "2025-01-01T00:00:00Z"); expect(result.rugStatus).toBe("LOW_RISK"); expect(result.informationCutoffAt >= before).toBe(true); expect((result.riskComponents as { components: unknown[] }).components).toHaveLength(11); });
  it("classifies a reliable honeypot flag as confirmed rug", async () => { const fetcher = vi.fn(async () => new Response(JSON.stringify({ data: { ownerAddress: null, freezeAuthority: null, freezeable: false, mutableMetadata: false, top10HolderPercent: 20, honeypot: true, isScam: false, nonTransferable: false, creatorAddress: "creator" } }), { status: 200 })); expect((await new BirdeyeTokenRiskProvider("key", fetcher).assess("mint", new Date().toISOString())).rugStatus).toBe("CONFIRMED_RUG"); });
});
