import{describe,expect,it}from"vitest";import{retrieveKnowledge,validateSystemLearnedRule,type KnowledgeRule}from"../src/domain/expert-knowledge";
const base:KnowledgeRule={id:"1",ruleKey:"risk.base",version:1,domain:"RISK_MANAGEMENT",topic:"risk",principle:"Inspect the distribution.",knowledgeType:"FOUNDATION",evidenceLevel:"REGULATORY",applicableAgents:["risk"],requiredContext:[],exceptions:[],tags:["tail"],sourceRefs:["source"],conflictsWith:[],effectiveAt:"2026-01-01T00:00:00Z",availableAt:"2026-01-02T00:00:00Z",deprecatedAt:null,status:"ACTIVE",systemLearnedEvidence:null};
describe("expert knowledge v1",()=>{
 it("enforces point-in-time availability",()=>expect(retrieveKnowledge([base],{agent:"risk",informationCutoffAt:"2026-01-01T12:00:00Z"}).selected).toHaveLength(0));
 it("requires declared context",()=>{const result=retrieveKnowledge([{...base,requiredContext:["liquidity"]}],{agent:"risk",informationCutoffAt:"2026-02-01T00:00:00Z"});expect(result.excluded[0].reason).toBe("REQUIRED_CONTEXT_MISSING")});
 it("preserves deprecation point-in-time",()=>{const rule={...base,deprecatedAt:"2026-03-01T00:00:00Z"};expect(retrieveKnowledge([rule],{agent:"risk",informationCutoffAt:"2026-02-01T00:00:00Z"}).selected).toHaveLength(1);expect(retrieveKnowledge([rule],{agent:"risk",informationCutoffAt:"2026-04-01T00:00:00Z"}).selected).toHaveLength(0)});
 it("surfaces conflicts without silently choosing",()=>{const other={...base,id:"2",ruleKey:"risk.other",conflictsWith:["risk.base"]};const left={...base,conflictsWith:["risk.other"]};expect(retrieveKnowledge([other,left],{agent:"risk",informationCutoffAt:"2026-04-01T00:00:00Z"}).conflicts).toEqual([{left:"risk.base",right:"risk.other"}])});
 it("is deterministic",()=>{const query={agent:"risk",informationCutoffAt:"2026-04-01T00:00:00Z"};expect(retrieveKnowledge([base],query).requestHash).toBe(retrieveKnowledge([base],query).requestHash)});
 it("rejects weak system-learned claims",()=>expect(()=>validateSystemLearnedRule({knowledgeType:"SYSTEM_LEARNED",evidenceLevel:"EMPIRICAL_SYSTEM",systemLearnedEvidence:{replayRunId:"r",outcomeRecordIds:["o"],sampleSize:3,dataQuality:100,outOfSampleValidated:true}})).toThrow("sample"));
});
