import { describe,expect,it } from "vitest"; import { evaluateFastFlow,findVerifiedConvergence,measureFastFlowLatency,type FastSafetyEvidence,type IndependenceEvidence,type VerifiedBuy } from "@/domain/fast-flow";
const buy=(id:string,wallet:string,second:number,quality=90):VerifiedBuy=>({eventId:id,eventEvidenceId:`event-${id}`,assetId:"asset",walletId:wallet,occurredAt:`2026-01-01T00:00:${String(second).padStart(2,"0")}.000Z`,availableAt:`2026-01-01T00:00:${String(second).padStart(2,"0")}.500Z`,verificationEvidenceId:`verify-${wallet}`,dataQuality:quality});
const independent:IndependenceEvidence={status:"confirmed",evidenceIds:["r1","r2","r3"],relationshipTypes:[],dataQuality:90}; const safe:FastSafetyEvidence={liquidityUsd:100000,liquidityQuality:90,liquidityEvidenceId:"liq",riskStatus:"LOW_RISK",riskQuality:90,riskEvidenceId:"risk",authorityCoverage:"complete"};
describe("Fast Flow v1",()=>{
  it("detects three unique verified wallets within 15 seconds",()=>expect(findVerifiedConvergence([buy("e1","w1",1),buy("e2","w2",5),buy("e3","w3",15)])).toHaveLength(1));
  it("records reproducible event and availability latency",()=>expect(measureFastFlowLatency([buy("e1","w1",1),buy("e2","w2",5),buy("e3","w3",15)],"2026-01-01T00:00:20.000Z")).toEqual({signalSpanMs:14000,lastEventAvailabilityToEvaluationMs:4500,firstEventToEvaluationMs:19000,evaluatedAt:"2026-01-01T00:00:20.000Z"}));
  it("does not count duplicate or low-quality wallets",()=>expect(findVerifiedConvergence([buy("e1","w1",1),buy("e2","w1",2),buy("e3","w2",3),buy("e4","w3",4,70)])).toEqual([]));
  it("passes only complete deterministic safety evidence",()=>expect(evaluateFastFlow([buy("e1","w1",1),buy("e2","w2",2),buy("e3","w3",3)],independent,safe)).toMatchObject({state:"fast_opportunity",blockers:[],opportunityScore:85}));
  it("keeps missing independence and risk evidence enriching",()=>{const result=evaluateFastFlow([buy("e1","w1",1),buy("e2","w2",2),buy("e3","w3",3)],{status:"unknown",evidenceIds:[],relationshipTypes:[],dataQuality:0},{...safe,riskStatus:"UNKNOWN",riskQuality:0,riskEvidenceId:null});expect(result.state).toBe("enriching");expect(result.riskScore).toBeNull();});
  it("vetoes related wallets and confirmed rugs",()=>{const result=evaluateFastFlow([buy("e1","w1",1),buy("e2","w2",2),buy("e3","w3",3)],{status:"related",evidenceIds:["rel"],relationshipTypes:["bot_cluster"],dataQuality:95},{...safe,riskStatus:"CONFIRMED_RUG"});expect(result.state).toBe("rejected");expect(result.blockers).toContain("wallet_relationship:bot_cluster");});
});
