import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { SupabaseClient } from "@supabase/supabase-js";
import { ExecutionFillSyncService } from "@/services/execution/fill-sync-service";
import type { ExecutionProvider, ProviderFillPage } from "@/services/execution/provider";
const accountId="00000000-0000-4000-8000-000000000123",now="2026-09-07T12:00:00.000Z";
const input={accountId,windowStart:"2026-09-01T00:00:00.000Z",windowEnd:"2026-09-07T11:59:59.000Z"};
const fill={providerFillId:"1",providerBillId:"99",providerOrderId:"7",clientOrderId:null,instrumentId:"BTC-USDT",side:"BUY" as const,quantity:"1",price:"100",feeAmount:"0",providerFeeAmount:"0",feeCurrency:"USDT",baseCurrency:"BTC",quoteCurrency:"USDT",quoteCurrencySource:"OKX_TRADE_QUOTE_CCY" as const,occurredAt:"2026-09-06T00:00:00.000Z",providerRecordedAt:"2026-09-06T00:00:00.001Z"};
const page=(overrides:Partial<Extract<ProviderFillPage,{status:"SUPPORTED"}>>={}):ProviderFillPage=>({status:"SUPPORTED",fills:[],nextCursor:null,exhausted:true,observedAt:now,window:{requestedStart:input.windowStart,requestedEnd:input.windowEnd,effectiveStart:input.windowStart,effectiveEnd:input.windowEnd,retentionStart:"2026-06-07T12:00:00.000Z",retentionLimited:false,source:"OKX_FILLS_HISTORY_3_MONTHS",timeBasis:"PROVIDER_RECORDED_AT"},...overrides});
function harness(){
  let saved:any=null,readError=false,rpcError=false;
  const account={id:accountId,provider:"okx-demo",provider_environment:"DEMO"};
  const db={from(table:string){const builder:any={select:()=>builder,eq:()=>builder,single:()=>Promise.resolve({data:account,error:readError?{}:null}),maybeSingle:()=>Promise.resolve({data:saved,error:readError?{}:null})};return builder},rpc:vi.fn(async(_name:string,{p_page:p}:any)=>{
    if(rpcError)return{data:null,error:{message:"fixture credential details never exposed"}};
    saved={...saved,id:"checkpoint",sync_key:p.sync_key,effective_start_at:p.effective_start_at,cursor_after_bill_id:p.next_cursor??p.request_cursor,status:p.status,exhausted:p.exhausted??false,retention_limited:p.retention_limited};
    return{data:{ok:true,checkpoint_id:"checkpoint",inserted:p.fills.length,cursor_after_bill_id:saved.cursor_after_bill_id,status:p.status,exhausted:saved.exhausted},error:null};
  })};
  const provider:ExecutionProvider={name:"okx-demo",mode:"DEMO",getFillsPage:vi.fn(async()=>page()),health:vi.fn(),getAccountState:vi.fn(),placeOrder:vi.fn(),getOrder:vi.fn(),cancelOrder:vi.fn()};
  return{db,provider,account,service:new ExecutionFillSyncService(db as unknown as SupabaseClient,provider),setSaved:(value:any)=>saved=value,failReads:()=>readError=true,failRpc:()=>rpcError=true};
}
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date(now))});afterEach(()=>vi.useRealTimers());
describe("bounded account fill sync (no network/database)",()=>{
  it("missing optional capability is explicit persisted UNSUPPORTED",async()=>{const h=harness();delete h.provider.getFillsPage;expect(await h.service.syncAccount(input)).toMatchObject({status:"UNSUPPORTED",pages:0,checkpointId:"checkpoint"});expect(h.db.rpc.mock.calls[0][1].p_page).toMatchObject({status:"UNSUPPORTED",fills:[]});expect(h.provider.placeOrder).not.toHaveBeenCalled()});
  it("provider unsupported is never complete",async()=>{const h=harness();vi.mocked(h.provider.getFillsPage!).mockResolvedValue({status:"UNSUPPORTED",reason:"SHADOW_NO_FILLS"});expect(await h.service.syncAccount(input)).toMatchObject({status:"UNSUPPORTED"})});
  it("atomically persists an explicit empty window, not account history",async()=>{const h=harness();expect(await h.service.syncAccount(input)).toEqual({status:"COMPLETE_WINDOW",checkpointId:"checkpoint",inserted:0,pages:1,reason:null});expect(h.db.rpc).toHaveBeenCalledWith("persist_execution_fill_page",expect.objectContaining({p_page:expect.objectContaining({account_id:accountId,provider:"okx-demo",provider_environment:"DEMO",time_basis:"PROVIDER_RECORDED_AT",requested_start_at:input.windowStart})}))});
  it("resumes the stored fixed window cursor and respects page budget",async()=>{const h=harness();h.setSaved({id:"checkpoint",cursor_after_bill_id:"9007199254740993999",effective_start_at:input.windowStart,exhausted:false});vi.mocked(h.provider.getFillsPage!).mockResolvedValue(page({fills:[{...fill,providerBillId:"9007199254740993998"}],exhausted:false,nextCursor:"9007199254740993998"}));expect(await h.service.syncAccount({...input,maxPages:1,pageSize:1})).toMatchObject({status:"PARTIAL",pages:1,reason:"PAGE_BUDGET_EXHAUSTED"});expect(h.provider.getFillsPage).toHaveBeenCalledWith(expect.objectContaining({afterBillId:"9007199254740993999",windowEnd:input.windowEnd}))});
  it("continues bounded pages without calling orders or account APIs",async()=>{const h=harness();vi.mocked(h.provider.getFillsPage!).mockResolvedValueOnce(page({fills:[fill],exhausted:false,nextCursor:"99"})).mockResolvedValueOnce(page());const pending=h.service.syncAccount({...input,maxPages:2,pageSize:1});await vi.runAllTimersAsync();expect(await pending).toMatchObject({status:"COMPLETE_WINDOW",pages:2});expect(h.provider.getAccountState).not.toHaveBeenCalled();expect(h.provider.getOrder).not.toHaveBeenCalled();expect(h.provider.placeOrder).not.toHaveBeenCalled();expect(h.provider.cancelOrder).not.toHaveBeenCalled()});
  it("rejects an empty non-exhausted retained page, never claiming progress",async()=>{const h=harness();vi.mocked(h.provider.getFillsPage!).mockResolvedValue(page({exhausted:false,nextCursor:"99"}));expect(await h.service.syncAccount(input)).toMatchObject({status:"FAILED",reason:"PROVIDER_FILL_PAGE_INVALID"});expect(h.db.rpc.mock.calls[0][1].p_page.fills).toEqual([])});
  it("retention-limited window remains a gap even after exhausted pagination",async()=>{const h=harness(),p=page();if(p.status!=="SUPPORTED")throw Error();p.window.effectiveStart="2026-09-02T00:00:00.000Z";p.window.retentionLimited=true;vi.mocked(h.provider.getFillsPage!).mockResolvedValue(p);expect(await h.service.syncAccount(input)).toMatchObject({status:"RETENTION_GAP",reason:"PROVIDER_RETENTION_LIMIT"})});
  it("saved exhausted checkpoint avoids rereading provider",async()=>{const h=harness();h.setSaved({id:"checkpoint",exhausted:true,retention_limited:false});expect(await h.service.syncAccount(input)).toMatchObject({status:"COMPLETE_WINDOW",pages:0});expect(h.provider.getFillsPage).not.toHaveBeenCalled()});
  it("provider failure persists FAILED, never raw credential errors",async()=>{const h=harness();vi.mocked(h.provider.getFillsPage!).mockRejectedValue(Error("fixture private credentials"));const result=await h.service.syncAccount(input);expect(result.status).toBe("FAILED");expect(JSON.stringify(result)).not.toContain("credentials");expect(h.db.rpc.mock.calls[0][1].p_page.status).toBe("FAILED")});
  it("unknown/mismatched account is rejected before provider read or persistence",async()=>{const h=harness();h.account.provider="other";expect(await h.service.syncAccount(input)).toMatchObject({status:"FAILED",reason:"FILL_SYNC_ACCOUNT_SCOPE_UNKNOWN"});expect(h.provider.getFillsPage).not.toHaveBeenCalled();expect(h.db.rpc).not.toHaveBeenCalled()});
  it("read errors do not call provider",async()=>{const h=harness();h.failReads();expect((await h.service.syncAccount(input)).status).toBe("FAILED");expect(h.provider.getFillsPage).not.toHaveBeenCalled()});
  it("RPC failure prevents any follow-on page",async()=>{const h=harness();h.failRpc();expect((await h.service.syncAccount(input)).status).toBe("FAILED");expect(h.provider.getFillsPage).toHaveBeenCalledOnce()});
  it.each([{maxPages:0},{maxPages:11},{pageSize:101},{accountId:"not-an-account"},{windowStart:"bad"},{windowEnd:"2027-01-01"}])("validates bounded input before reads/effects %j",async override=>{const h=harness();expect((await h.service.syncAccount({...input,...override})).reason).toBe("FILL_SYNC_INPUT_INVALID");expect(h.provider.getFillsPage).not.toHaveBeenCalled();expect(h.db.rpc).not.toHaveBeenCalled()});
});
