import { describe, expect, it } from "vitest";
import { appendOpportunityRevision, assertValidTransition, opportunityIdempotencyKey, rebuildOpportunity, validateOpportunityRevision, type OpportunityAggregate, type OpportunityRevisionInput } from "@/domain/opportunities";

const revision = (changes: Partial<OpportunityRevisionInput> = {}): OpportunityRevisionInput => ({ opportunityId: "opportunity-1", revisionNumber: 1, revisionType: "v0_fast_safety", currentState: "detected", nextState: "enriching", createdAt: "2026-01-01T00:00:10.000Z", informationCutoffAt: "2026-01-01T00:00:09.000Z", triggerEventId: "event-1", evidenceRefs: [{ evidenceId: "evidence-1", evidenceType: "wallet_transaction", availableAt: "2026-01-01T00:00:08.000Z", payloadHash: "a".repeat(64) }], agentOutputs: {}, safetyResult: { status: "pending" }, ...changes });

describe("Opportunity Aggregate v1", () => {
  it("accepts valid and rejects invalid transitions", () => { expect(() => assertValidTransition("detected", "enriching")).not.toThrow(); expect(() => assertValidTransition("rejected", "qualified")).toThrow(/Invalid opportunity transition/); });
  it("prevents duplicate opportunities through a deterministic identity", () => { const input = { assetId: "asset", opportunityType: "convergence", createdFromEventId: "event" }; expect(opportunityIdempotencyKey(input)).toBe(opportunityIdempotencyKey(input)); expect(opportunityIdempotencyKey({ ...input, createdFromEventId: "other" })).not.toBe(opportunityIdempotencyKey(input)); });
  it("appends immutably and refuses duplicate revisions", () => { const aggregate: OpportunityAggregate = Object.freeze({ opportunityId: "opportunity-1", state: "detected", currentRevision: 0, revisions: Object.freeze([]) }); const next = appendOpportunityRevision(aggregate, revision()); expect(aggregate.currentRevision).toBe(0); expect(next).toMatchObject({ state: "enriching", currentRevision: 1 }); expect(() => appendOpportunityRevision(next, revision({ revisionNumber: 2, currentState: "enriching" }))).toThrow(/Duplicate opportunity revision/); });
  it("actively rejects evidence from the future", () => { expect(() => validateOpportunityRevision(revision({ evidenceRefs: [{ evidenceId: "future", evidenceType: "risk", availableAt: "2026-01-01T00:00:10.000Z", payloadHash: "b".repeat(64) }] }))).toThrow(/Future evidence rejected/); });
  it("rebuilds deterministically and rejects sequence gaps", () => { const revisions = [revision(), revision({ revisionNumber: 2, currentState: "enriching", nextState: "watch", revisionType: "v2_risk_liquidity", triggerEventId: "event-2" })]; expect(rebuildOpportunity("detected", revisions)).toBe("watch"); expect(rebuildOpportunity("detected", [...revisions].reverse())).toBe("watch"); expect(() => rebuildOpportunity("detected", [revision({ revisionNumber: 2 })])).toThrow(/sequence has a gap/); });
});
