import { describe, expect, it } from "vitest";
import { aggregateQualifications, evaluateQualification, type QualificationInput } from "@/domain/qualification";
const cutoff = "2026-08-17T12:00:00.000Z";
function input(overrides: Partial<QualificationInput> = {}): QualificationInput { return { candidateId:"c1",candidateRevision:1,currentState:"ACCELERATING",informationCutoffAt:cutoff,safety:"PASS",dataQuality:90,liquidityUsd:50_000,rawWalletCount:4,independentWallets:3,verifiedWallets:3,relationshipCoverage:90,riskCoverage:90,priceAcceleration:true,volumeAcceleration:true,latenessMs:1_000,marketCapUsd:1_000_000,tokenAgeSeconds:300,newWalletInflow:true,holderGrowth:null,holderProviderAvailable:false,evidence:{},...overrides }; }
describe("qualification diagnostics v1",()=>{
  it("qualifies when all applicable requirements pass",()=>{const r=evaluateQualification(input());expect(r.finalDecision).toBe("QUALIFIED");expect(r.decisionReason).toBe("PASS");expect(r.requirements.find(x=>x.key==="holder_growth")?.status).toBe("NOT_APPLICABLE")});
  it("separates an explicit failure as a true negative",()=>{const r=evaluateQualification(input({dataQuality:67}));expect(r.finalDecision).toBe("REJECTED");expect(r.decisionReason).toBe("TRUE_NEGATIVE");expect(r.requirements.find(x=>x.key==="minimum_data_quality")?.status).toBe("FAIL")});
  it("keeps unknown safety as data blocked",()=>{const r=evaluateQualification(input({safety:"UNKNOWN"}));expect(r.finalDecision).toBe("WATCH");expect(r.decisionReason).toBe("DATA_BLOCKED")});
  it("keeps unknown liquidity distinct from fail",()=>{const r=evaluateQualification(input({liquidityUsd:null}));expect(r.requirements.find(x=>x.key==="liquidity_evidence")?.status).toBe("UNKNOWN");expect(r.finalDecision).toBe("WATCH")});
  it("represents insufficient risk coverage as unknown coverage",()=>{const r=evaluateQualification(input({riskCoverage:42}));const risk=r.requirements.find(x=>x.key==="token_risk_coverage");expect(risk?.status).toBe("UNKNOWN");expect(risk?.blockerCode).toBe("RISK_COVERAGE_INSUFFICIENT_UNKNOWN")});
  it("rejects future evidence",()=>expect(()=>evaluateQualification(input({evidence:{safety:[{type:"risk",id:"future",availableAt:"2026-08-18T00:00:00.000Z"}]}}))).toThrow("FUTURE_EVIDENCE_REJECTED"));
  it("creates a new deterministic result for a newer revision",()=>{const a=evaluateQualification(input()),b=evaluateQualification(input({candidateRevision:2,rawWalletCount:5}));expect(a.inputHash).not.toBe(b.inputHash);expect(evaluateQualification(input()).inputHash).toBe(a.inputHash)});
  it("does not mutate a historical evaluation",()=>{const a=evaluateQualification(input()),snapshot=JSON.stringify(a);evaluateQualification(input({candidateRevision:2,dataQuality:50}));expect(JSON.stringify(a)).toBe(snapshot)});
  it("aggregates blockers and unknowns separately",()=>{const fail=evaluateQualification(input({dataQuality:50})),unknown=evaluateQualification(input({liquidityUsd:null})),a=aggregateQualifications([fail,unknown]);expect(a.blockerFrequency.DATA_QUALITY_BELOW_THRESHOLD).toBe(1);expect(a.unknownFrequency.liquidity_evidence).toBe(1);expect(a.policyStrictness.trueNegative).toBe(1);expect(a.policyStrictness.dataBlocked).toBe(1)});
});
