import { describe, expect, it } from "vitest";
import { evaluateStrategyValidation, VALIDATION_PROTOCOL_V1, type ValidationTrade } from "../src/domain/strategy-validation";

function trades(count = 40, loserEvery = 4): ValidationTrade[] { return Array.from({ length: count }, (_, index) => { const entered = new Date(Date.UTC(2026, 0, 1 + Math.floor(index / 4), index % 4)).toISOString(); const r = index % loserEvery === 0 ? -0.5 : 0.8; return { tradeId: `trade-${index}`, assetId: `asset-${index % 4}`, enteredAt: entered, exitedAt: new Date(Date.parse(entered) + 60_000).toISOString(), rMultiple: r, modeledLiveR: r - 0.05, stressR: r - 0.1, regime: index % 2 ? "RISK_ON" : "SIDEWAYS", availableAt: new Date(Date.parse(entered) + 60_000).toISOString() }; }); }
function input(source = trades()) { return { strategyId: "orb", strategyVersion: 1, phase: "OUT_OF_SAMPLE" as const, windowStart: "2026-01-01T00:00:00.000Z", windowEnd: "2026-02-01T00:00:00.000Z", informationCutoffAt: "2026-02-01T00:00:00.000Z", datasetHash: "dataset-1", hypothesisId: "hypothesis-1", invalidationCondition: "close back inside opening range", dataQuality: 95, independentPeriods: 3, trades: source } as const; }

describe("strategy validation protocol v1", () => {
  it("approves only when every independent gate passes", () => { const result = evaluateStrategyValidation(input()); expect(result.decision).toBe("APPROVED"); expect(result.gates.every((gate) => gate.status === "PASS")).toBe(true); });
  it("returns insufficient data instead of fabricating confidence from a small sample", () => { const result = evaluateStrategyValidation(input(trades(5))); expect(result.decision).toBe("INSUFFICIENT_DATA"); expect(result.gates.find((gate) => gate.code === "SAMPLE_SIZE")?.status).toBe("UNKNOWN"); });
  it("keeps missing modeled live evidence UNKNOWN", () => { const source = trades().map((trade) => ({ ...trade, modeledLiveR: null })); const result = evaluateStrategyValidation(input(source)); expect(result.decision).toBe("INSUFFICIENT_DATA"); expect(result.gates.find((gate) => gate.code === "MODELED_LIVE_EXPECTANCY")?.status).toBe("UNKNOWN"); });
  it("rejects future evidence", () => { const source = trades(); source[0] = { ...source[0], availableAt: "2026-03-01T00:00:00.000Z" }; expect(() => evaluateStrategyValidation(input(source))).toThrow("FUTURE_TRADE_EVIDENCE_REJECTED"); });
  it("is deterministic and does not depend on input ordering", () => { const first = evaluateStrategyValidation(input()); const second = evaluateStrategyValidation(input([...trades()].reverse())); expect(first.validationKey).toBe(second.validationKey); expect(first.resultHash).toBe(second.resultHash); });
  it("detects dependence on one best trade", () => { const source = trades(); source[0] = { ...source[0], rMultiple: 50, modeledLiveR: 49, stressR: 48 }; const result = evaluateStrategyValidation(input(source), { ...VALIDATION_PROTOCOL_V1, maximumTopTradePnlShare: 0.2 }); expect(result.gates.find((gate) => gate.code === "BEST_TRADE_DEPENDENCE")?.status).toBe("FAIL"); });
});
