import {describe,expect,it}from"vitest";import{assessPair,evaluateWalletIndependence,type SourceClassification,type WalletRelationshipFeature}from"@/domain/wallet-clustering";
const feature=(walletId:string,changes:Partial<WalletRelationshipFeature>={}):WalletRelationshipFeature=>({walletId,dataQuality:90,historyComplete:true,firstSeenAt:"2026-01-01T00:00:00.000Z",firstFundingAt:"2026-01-01T00:00:00.000Z",funderAddress:null,fundingSourceClassification:"unknown",counterparties:[],tradeTimesByAsset:{},...changes});
describe("wallet independence v1",()=>{
  it.each(["exchange","bridge","program"] as SourceClassification[])("does not treat a common %s funder as same owner",source=>{const pair=assessPair(feature("a",{funderAddress:"service",fundingSourceClassification:source}),feature("b",{funderAddress:"service",fundingSourceClassification:source,firstSeenAt:"2026-02-01T00:00:00.000Z"}));expect(pair.status).toBe("independent");expect(pair.evidence.find(x=>x.evidenceType==="common_funder")).toMatchObject({classification:"shared_service",supportsCluster:false});});
  it("keeps synchronized trades as evidence rather than proof",()=>{const trades={token:["2026-01-01T00:00:01Z","2026-01-02T00:00:01Z","2026-01-03T00:00:01Z"]};const pair=assessPair(feature("a",{tradeTimesByAsset:trades}),feature("b",{tradeTimesByAsset:trades}));expect(pair.evidence.find(x=>x.evidenceType==="synchronized_behavior")?.supportsCluster).toBe(true);expect(pair.status).toBe("unknown");});
  it("returns UNKNOWN adjusted count below relationship coverage",()=>{const result=evaluateWalletIndependence([feature("a"),feature("b",{historyComplete:false}),feature("c",{historyComplete:false})]);expect(result.relationshipCoverage).toBeLessThan(80);expect(result.clusterAdjustedCount).toBeNull();expect(result.status).toBe("unknown");});
  it("allows UNKNOWN to become related in a new immutable evaluation input",()=>{const early=evaluateWalletIndependence([feature("a",{historyComplete:false}),feature("b",{historyComplete:false})]);const evidence={funderAddress:"private-funder",fundingSourceClassification:"wallet" as const,counterparties:["x","y","z","q","r"],tradeTimesByAsset:{token:["2026-01-01T00:00:01Z","2026-01-02T00:00:01Z","2026-01-03T00:00:01Z"]}};const later=evaluateWalletIndependence([feature("a",evidence),feature("b",evidence)]);expect(early.memberships[0].relationshipStatus).toBe("unknown");expect(later.memberships[0].relationshipStatus).toBe("clustered");expect(early.memberships[0].relationshipStatus).toBe("unknown");});
  it("produces a deterministic cluster-adjusted count only with sufficient coverage",()=>{const evidence={funderAddress:"private",fundingSourceClassification:"wallet" as const,counterparties:["1","2","3","4","5"],tradeTimesByAsset:{t:["2026-01-01T00:00:01Z","2026-01-02T00:00:01Z","2026-01-03T00:00:01Z"]}};const independent=feature("c",{firstSeenAt:"2026-03-01T00:00:00.000Z"});const result=evaluateWalletIndependence([feature("a",evidence),feature("b",evidence),independent]);expect(result.status).toBe("available");expect(result.memberships.filter(x=>x.relationshipStatus==="clustered")).toHaveLength(2);expect(result.clusterAdjustedCount).not.toBeNull();expect(evaluateWalletIndependence([independent,feature("b",evidence),feature("a",evidence)]).clusterAdjustedCount).toBe(result.clusterAdjustedCount);});
});
