import type { SupabaseClient } from "@supabase/supabase-js";
import { deterministicDigest } from "@/domain/events";
import { advanceReplay, HISTORICAL_REPLAY_VERSION, REPLAY_ORDERING_VERSION, replayDatasetHash, type ReplaySourceItem, type ReplayState } from "@/domain/historical-replay";
import { SimulationService } from "@/services/simulation/service";

export interface HistoricalReplayRequest { startsAt:string; endsAt:string; batchSize?:number; }
export class HistoricalReplayService {
  constructor(private db:SupabaseClient){}
  async run(request:HistoricalReplayRequest){
    if(Date.parse(request.startsAt)>=Date.parse(request.endsAt))throw new Error("Replay end must be after start");
    const items=await this.loadItems(request),datasetHash=replayDatasetHash(items),inputHash=deterministicDigest({startsAt:request.startsAt,endsAt:request.endsAt,replayVersion:HISTORICAL_REPLAY_VERSION,orderingVersion:REPLAY_ORDERING_VERSION,datasetHash});
    let{data:run,error}=await this.db.from("historical_replay_runs").select("*").eq("input_hash",inputHash).maybeSingle();if(error)throw error;
    if(run?.status==="COMPLETED"){const simulationRunId=await this.attachSimulation(run.id,run.simulation_run_id,request);return{runId:run.id,reused:true,processed:run.items_processed,datasetHash,simulationRunId};}
    if(!run){const created=await this.db.from("historical_replay_runs").insert({replay_version:HISTORICAL_REPLAY_VERSION,ordering_version:REPLAY_ORDERING_VERSION,status:"RUNNING",starts_at:request.startsAt,ends_at:request.endsAt,current_replay_time:request.startsAt,information_cutoff_policy:"strict-available-at-v1",dataset_hash:datasetHash,input_hash:inputHash}).select("*").single();if(created.error)throw created.error;run=created.data;}
    try{
      const{data:checkpoint,error:cpError}=await this.db.from("historical_replay_checkpoints").select("*").eq("replay_run_id",run.id).order("sequence_number",{ascending:false}).limit(1).maybeSingle();if(cpError)throw cpError;
      let previous=(checkpoint?.state??null) as ReplayState|null,sequence=previous?.processed??0,hasMore=true;
      while(hasMore){const step=advanceReplay(items,previous,request.endsAt,request.batchSize??250);if(step.batch.length){const rows=step.batch.map((item,index)=>({replay_run_id:run.id,sequence_number:sequence+index+1,item_kind:item.kind,source_id:item.sourceId,asset_id:item.assetId,entity_id:item.entityId,occurred_at:item.occurredAt,available_at:item.availableAt,replayed_at:item.availableAt,summary:item.summary,state:item.state,data_quality:item.dataQuality,evidence_refs:item.evidenceRefs,item_hash:deterministicDigest(item)}));const inserted=await this.db.from("historical_replay_items").upsert(rows,{onConflict:"replay_run_id,item_kind,source_id",ignoreDuplicates:true});if(inserted.error)throw inserted.error;sequence=step.state.processed;const saved=await this.db.from("historical_replay_checkpoints").upsert({replay_run_id:run.id,sequence_number:sequence,replay_time:request.endsAt,information_available_through:step.state.cursor?.availableAt??request.startsAt,state:step.state,state_hash:step.stateHash},{onConflict:"replay_run_id,sequence_number",ignoreDuplicates:true});if(saved.error)throw saved.error;}previous=step.state;hasMore=step.hasMore;if(!step.batch.length)break;}
      const completed=await this.db.from("historical_replay_runs").update({status:"COMPLETED",current_replay_time:request.endsAt,items_processed:sequence,completed_at:new Date().toISOString(),last_error:null}).eq("id",run.id);if(completed.error)throw completed.error;const simulationRunId=await this.attachSimulation(run.id,null,request);return{runId:run.id,reused:false,processed:sequence,datasetHash,state:previous,simulationRunId};
    }catch(cause){await this.db.from("historical_replay_runs").update({status:"FAILED",last_error:cause instanceof Error?cause.message:String(cause)}).eq("id",run.id);throw cause;}
  }
  private async attachSimulation(replayRunId:string,current:string|null,request:HistoricalReplayRequest){if(current)return current;const simulation=await new SimulationService(this.db).run({initialCapitalSek:20_000,startsAt:request.startsAt,endsAt:request.endsAt,policy:"FIXED_SMALL"});const saved=await this.db.from("historical_replay_runs").update({simulation_run_id:simulation.runId}).eq("id",replayRunId);if(saved.error)throw saved.error;return simulation.runId;}
  private async loadItems(request:HistoricalReplayRequest):Promise<ReplaySourceItem[]>{
    const[{data:events,error:eventError},{data:revisions,error:revisionError},{data:qualifications,error:qError},{data:catalystRevisions,error:cError},{data:forecasts,error:fError},{data:knowledgeRules,error:kError},{data:knowledgeRetrievals,error:krError}]=await Promise.all([
      this.db.from("event_outbox").select("event_id,event_type,entity_id,asset_id,occurred_at,available_at,data_quality,provider,source_reference").gte("available_at",request.startsAt).lte("available_at",request.endsAt).order("available_at"),
      this.db.from("jackpot_candidate_revisions").select("id,candidate_id,revision_number,revision_type,state,information_cutoff_at,available_at,evidence_refs,jackpot_candidates!inner(asset_id)").gte("available_at",request.startsAt).lte("available_at",request.endsAt).order("available_at"),
      this.db.from("qualification_evaluations").select("id,candidate_id,candidate_revision,final_decision,decision_reason,information_cutoff_at,evaluated_at,requirements_passed,requirements_failed,requirements_unknown,qualification_requirements(evidence_refs)").gte("evaluated_at",request.startsAt).lte("evaluated_at",request.endsAt).order("evaluated_at"),
      this.db.from("catalyst_revisions").select("id,catalyst_id,state,occurred_at,available_at,materiality,evidence_refs,catalysts!inner(asset_id)").gte("available_at",request.startsAt).lte("available_at",request.endsAt).order("available_at"),
      this.db.from("forecasts").select("id,asset_id,catalyst_id,horizon,status,reason,information_cutoff_at,available_at,data_quality,evidence_refs").gte("available_at",request.startsAt).lte("available_at",request.endsAt).order("available_at"),
      this.db.from("knowledge_rules").select("id,rule_key,version,domain,topic,status,available_at,effective_at,evidence_level").gte("available_at",request.startsAt).lte("available_at",request.endsAt).order("available_at"),
      this.db.from("knowledge_retrieval_traces").select("id,request_hash,agent,information_cutoff_at,available_at,selected_rule_refs").gte("available_at",request.startsAt).lte("available_at",request.endsAt).order("available_at"),
    ]);if(eventError)throw eventError;if(revisionError)throw revisionError;if(qError)throw qError;if(cError)throw cError;if(fError)throw fError;if(kError)throw kError;if(krError)throw krError;
    const items:ReplaySourceItem[]=[];
    for(const x of events??[])items.push({kind:"EVENT",sourceId:x.event_id,availableAt:x.available_at,occurredAt:x.occurred_at,assetId:x.asset_id,entityId:x.entity_id,summary:`${x.event_type} · ${x.provider}`,state:null,dataQuality:x.data_quality,evidenceRefs:[x.source_reference]});
    for(const x of revisions??[]){const candidate=Array.isArray(x.jackpot_candidates)?x.jackpot_candidates[0]:x.jackpot_candidates;items.push({kind:"CANDIDATE_REVISION",sourceId:x.id,availableAt:x.available_at,occurredAt:x.information_cutoff_at,assetId:candidate?.asset_id??null,entityId:x.candidate_id,summary:`${x.revision_type} · revision ${x.revision_number}`,state:x.state,dataQuality:null,evidenceRefs:Array.isArray(x.evidence_refs)?x.evidence_refs.map(refId):[]});}
    for(const x of qualifications??[]){const refs=(x.qualification_requirements??[]).flatMap((r:any)=>Array.isArray(r.evidence_refs)?r.evidence_refs.map(refId):[]);items.push({kind:"QUALIFICATION",sourceId:x.id,availableAt:x.evaluated_at,occurredAt:x.information_cutoff_at,assetId:null,entityId:x.candidate_id,summary:`${x.final_decision} · ${x.decision_reason}`,state:x.final_decision,dataQuality:null,evidenceRefs:[...new Set(refs)]});}
    for(const x of catalystRevisions??[]){const catalyst=Array.isArray(x.catalysts)?x.catalysts[0]:x.catalysts;items.push({kind:"CATALYST_REVISION",sourceId:x.id,availableAt:x.available_at,occurredAt:x.occurred_at,assetId:catalyst?.asset_id??null,entityId:x.catalyst_id,summary:`${x.state} · ${x.materiality}`,state:x.state,dataQuality:null,evidenceRefs:(x.evidence_refs??[]).map(refId)});}
    for(const x of forecasts??[])items.push({kind:"FORECAST",sourceId:x.id,availableAt:x.available_at,occurredAt:x.information_cutoff_at,assetId:x.asset_id,entityId:x.catalyst_id??x.id,summary:`${x.horizon} · ${x.status}${x.reason?` · ${x.reason}`:""}`,state:x.status,dataQuality:num(x.data_quality),evidenceRefs:(x.evidence_refs??[]).map(refId)});
    for(const x of knowledgeRules??[])items.push({kind:"KNOWLEDGE_RULE",sourceId:x.id,availableAt:x.available_at,occurredAt:x.effective_at,assetId:null,entityId:x.rule_key,summary:`${x.domain} · ${x.topic} · v${x.version}`,state:x.status,dataQuality:null,evidenceRefs:[x.evidence_level]});
    for(const x of knowledgeRetrievals??[])items.push({kind:"KNOWLEDGE_RETRIEVAL",sourceId:x.id,availableAt:x.available_at,occurredAt:x.information_cutoff_at,assetId:null,entityId:x.request_hash,summary:`${x.agent} · ${(x.selected_rule_refs??[]).length} rules`,state:null,dataQuality:null,evidenceRefs:(x.selected_rule_refs??[]).map(refId)});
    return items;
  }
}
function refId(value:any){return typeof value==="string"?value:String(value?.id??value?.evidenceId??deterministicDigest(value));}
function num(value:unknown){const n=Number(value);return value===null||value===undefined||!Number.isFinite(n)?null:n}
