import type { SupabaseClient } from "@supabase/supabase-js";
import { createStrategyAttribution, type StrategyAttributionInput } from "@/domain/strategy-attribution";
export class StrategyAttributionService {
 constructor(private db:SupabaseClient){}
 async register(input:StrategyAttributionInput){
  const a=createStrategyAttribution(input),existing=await this.db.from("strategy_attribution_contexts").select("id").eq("attribution_key",a.attributionKey).maybeSingle();if(existing.error)throw existing.error;if(existing.data)return{id:existing.data.id,...a};
  if(a.status==="KNOWN"){const[d,v,r]=await Promise.all([this.db.from("strategy_definitions").select("id,version,available_at").eq("id",a.strategyDefinitionId!).single(),this.db.from("strategy_validation_runs").select("id,strategy_definition_id,available_at").eq("id",a.validationRunId!).single(),a.runtimeAssessmentId?this.db.from("strategy_runtime_assessments").select("id,strategy_definition_id,validation_run_id,available_at").eq("id",a.runtimeAssessmentId).single():Promise.resolve({data:null,error:null})]);if(d.error)throw d.error;if(v.error)throw v.error;if(r.error)throw r.error;if(d.data.version!==a.strategyVersion||v.data.strategy_definition_id!==a.strategyDefinitionId)throw new Error("STRATEGY_ATTRIBUTION_VERSION_MISMATCH");if(r.data&&(r.data.strategy_definition_id!==a.strategyDefinitionId||r.data.validation_run_id!==a.validationRunId))throw new Error("STRATEGY_ATTRIBUTION_RUNTIME_MISMATCH");for(const at of[d.data.available_at,v.data.available_at,r.data?.available_at])if(at&&Date.parse(at)>Date.parse(a.informationCutoffAt))throw new Error("FUTURE_STRATEGY_ATTRIBUTION_EVIDENCE_REJECTED")}
  const saved=await this.db.from("strategy_attribution_contexts").insert({attribution_key:a.attributionKey,contract_version:a.contractVersion,status:a.status,strategy_definition_id:a.strategyDefinitionId,strategy_version:a.strategyVersion,validation_run_id:a.validationRunId,runtime_assessment_id:a.runtimeAssessmentId,information_cutoff_at:a.informationCutoffAt,available_at:a.availableAt,payload_hash:a.payloadHash}).select("id").single();if(saved.error?.code==="23505"){const retry=await this.db.from("strategy_attribution_contexts").select("id").eq("attribution_key",a.attributionKey).single();if(retry.error)throw retry.error;return{id:retry.data.id,...a}}if(saved.error)throw saved.error;return{id:saved.data.id,...a};
 }
}
