import { createServiceClient } from "@/lib/supabase/server";
import { STRATEGY_RESEARCH_CATALOG } from "@/domain/strategy-pattern-lab";
import { BacktestWorkspace } from "./backtest-workspace";
import { initialLabValues, requestedLabRun, type LabSearch } from "./lab-workspace-state";
import { loadLabRunResult } from "./run-result-data";
import styles from "./strategy-lab.module.css";

export const dynamic = "force-dynamic";
export default async function StrategyLabPage({ searchParams }: { searchParams: Promise<LabSearch> }) {
  const search = await searchParams;
  const requestedRunId = requestedLabRun(search);
  const db = createServiceClient();
  const [{ data: runs }, { data: definitions }, { data: sources }, { data: snapshots }, { data: selections }, { data: assets }, selectedResult] = await Promise.all([
    db.from("strategy_evaluation_runs").select("*,assets(symbol),strategy_definitions(name,strategy_key,version,timeframe)").order("created_at", { ascending: false }).limit(30),
    db.from("strategy_definitions").select("*").order("created_at", { ascending: false }).limit(20),
    db.from("candle_sources").select("*,assets(symbol)").order("updated_at", { ascending: false }).limit(20),
    db.from("strategy_performance_snapshots").select("*,assets(symbol),strategy_definitions(name,strategy_key,version)").order("created_at", { ascending: false }).limit(30),
    db.from("strategy_selector_runs").select("*,assets(symbol)").order("created_at", { ascending: false }).limit(10),
    db.from("assets").select("id,symbol,kind").eq("is_active", true).order("symbol"),
    loadLabRunResult(db, requestedRunId),
  ]);
  const researchRank = new Map(STRATEGY_RESEARCH_CATALOG.map(item => [item.definition.strategyId, item.researchPriority]));
  const researchRationale = new Map(STRATEGY_RESEARCH_CATALOG.map(item => [item.definition.strategyId, item.rationale]));
  const researchDefinitions = (definitions ?? []).filter((item: any) => researchRank.has(item.strategy_key)).sort((a: any, b: any) => (researchRank.get(a.strategy_key) ?? 99) - (researchRank.get(b.strategy_key) ?? 99));
  const runnableAssetIds = new Set((sources ?? []).filter((item: any) => item.enabled && item.status !== "FAILED").map((item: any) => item.asset_id));
  const runnableAssets = (assets ?? []).filter((item: any) => runnableAssetIds.has(item.id));
  const formValues = initialLabValues(search, {
    definitionId: researchDefinitions[0]?.id ?? "", assetId: runnableAssets[0]?.id ?? "",
    startsAt: new Date(Date.now() - 90 * 86_400_000).toISOString().slice(0, 10),
    endsAt: new Date().toISOString().slice(0, 10), sourceId: (sources ?? []).find((item: any) => item.enabled)?.id ?? "",
  });
  return <main className={styles.page}>
    <section className={styles.hero}><p>DETERMINISTIC RESEARCH</p><h1>Strategy Pattern Lab</h1><span>Versionerade setups, point-in-time candles och reproducerbar performance. Inga live-order.</span></section>
    <section className={styles.summary}><Metric label="Research candidates" value={`${researchDefinitions.length}/10`}/><Metric label="Performance snapshots" value={String(snapshots?.length ?? 0)}/><Metric label="Execution" value="DISABLED"/></section>
    <BacktestWorkspace initialValues={formValues} requestedRunId={requestedRunId} result={selectedResult}
      runs={(runs ?? []).map((run: any) => ({ id: run.id, label: `${asset(run.assets)} · ${run.strategy_definitions?.name ?? "UNKNOWN"} · ${run.trade_count} trades · ${run.created_at} · ${run.id.slice(0, 8)}` }))}
      definitions={researchDefinitions.map((item:any) => ({ id:item.id,name:`#${researchRank.get(item.strategy_key)} · ${item.name}`,timeframe:item.timeframe }))}
      assets={runnableAssets.map((item:any) => ({ id:item.id,symbol:item.symbol,kind:item.kind }))}
      sources={(sources ?? []).filter((item:any) => item.enabled).map((item:any) => ({ id:item.id,label:`${asset(item.assets)} · ${item.timeframe} · ${item.provider}`,status:item.status }))}/>
    <section className={styles.panel}><header><div><p>TOP 10 RESEARCH QUEUE</p><h2>Strategy candidates</h2></div><span>UNPROVEN tills vår egen historiska validering visar edge</span></header>{researchDefinitions.length ? <div className={styles.grid}>{researchDefinitions.map((item: any) => <article key={item.id}><small>#{researchRank.get(item.strategy_key)} · UNPROVEN · {item.market} · {item.timeframe} · v{item.version}</small><h3>{item.name}</h3><p className={styles.muted}>{researchRationale.get(item.strategy_key)}</p><div className={styles.rules}><Rule label="Setup" value={item.setup_type}/><Rule label="Opening range" value={item.definition?.openingRangeMinutes ? `${item.definition.openingRangeMinutes} min` : "N/A"}/><Rule label="Confirmation" value={item.definition?.requireRetest ? "Breakout close + retest" : item.definition?.breakoutConfirmation ?? "Rule-defined"}/><Rule label="Volume filter" value={item.definition?.minimumBreakoutVolumeMultiple ? `${item.definition.minimumBreakoutVolumeMultiple}× baseline` : "N/A"}/><Rule label="Target" value={item.definition?.targetR ? `${item.definition.targetR}R` : item.definition?.targetPolicy ?? "UNKNOWN"}/><Rule label="Minimum samples" value={String(item.definition?.minimumSampleSize ?? "UNKNOWN")}/></div><footer>Available {new Date(item.available_at).toLocaleString("sv-SE")}</footer></article>)}</div> : <div className={styles.empty}><strong>NO DEFINITIONS</strong><span>Applicera migration 0054 för att registrera research-katalogen.</span></div>}</section>
    <section className={styles.panel}><header><div><p>HISTORICAL DATA</p><h2>Candle providers</h2></div><span>Point-in-time OHLCV ingestion</span></header>{sources?.length ? <div className={styles.grid}>{sources.map((source: any) => <article key={source.id}><small>{asset(source.assets)} · {source.timeframe} · {source.provider}</small><h3>{source.status}</h3><footer>{source.last_successful_sync ? `Synced ${new Date(source.last_successful_sync).toLocaleString("sv-SE")}` : "Never synced"}{source.last_error ? " · Datakällan rapporterade ett fel. Detaljer finns endast i den skyddade driftloggen." : ""}</footer></article>)}</div> : <div className={styles.empty}><strong>NO SOURCES</strong><span>Ingen candle-provider är konfigurerad.</span></div>}</section>
    <section className={styles.panel}><header><div><p>STRATEGY SELECTOR</p><h2>Context fit ranking</h2></div><span>Expected value, drawdown, sample, context och datakvalitet</span></header>{selections?.length ? <div className={styles.grid}>{selections.map((selection: any) => <article key={selection.id}><small>{asset(selection.assets)} · {selection.timeframe} · {selection.session} · {selection.regime}</small><h3>{selection.status}</h3>{selection.ranked_strategies?.length ? <div className={styles.ranking}>{selection.ranked_strategies.slice(0, 5).map((rank: any, index: number) => <div key={`${selection.id}-${rank.snapshotKey ?? rank.strategyId}-${rank.strategyVersion}-${index}`}><b>#{index + 1} {rank.strategyId} v{rank.strategyVersion}</b><span>{rank.status} · fit {rank.fitScore ?? "UNKNOWN"} · n={rank.sampleSize}</span></div>)}</div> : <p className={styles.muted}>Ingen strategi hade tillräckligt verifierad historik.</p>}<footer>Cutoff {new Date(selection.information_cutoff_at).toLocaleString("sv-SE")} · {selection.selector_version}</footer></article>)}</div> : <div className={styles.empty}><strong>NO STRATEGY ELIGIBLE</strong><span>Selector-workern har ännu inte tillräckliga performance-snapshots.</span></div>}</section>
    <section className={styles.panel}><header><div><p>PERFORMANCE STORE</p><h2>Immutable research snapshots</h2></div><span>Validation/OOS-resultat separerade från strategy definitions</span></header>{snapshots?.length ? <div className={styles.grid}>{snapshots.map((snapshot: any) => <article key={snapshot.id}><small>{asset(snapshot.assets)} · {snapshot.timeframe} · {snapshot.dataset_split}</small><h3>{snapshot.strategy_definitions?.name}</h3><div className={styles.metrics}><Metric label="Status" value={snapshot.status}/><Metric label="Samples" value={String(snapshot.sample_size)}/><Metric label="EV (R)" value={metric(snapshot.metrics?.expectedValueR)}/><Metric label="Profit factor" value={metric(snapshot.metrics?.profitFactor)}/><Metric label="Median R" value={metric(snapshot.metrics?.medianReturnR)}/><Metric label="Max DD (R)" value={metric(snapshot.metrics?.maxDrawdownR)}/></div><footer>{snapshot.session} · {snapshot.regime} · cutoff {new Date(snapshot.information_cutoff_at).toLocaleString("sv-SE")}</footer></article>)}</div> : <div className={styles.empty}><strong>INSUFFICIENT DATA</strong><span>Inga versionerade performance-snapshots har skapats ännu.</span></div>}</section>
    <section className={styles.panel}><header><div><p>IMMUTABLE RESULTS</p><h2>Historical evaluations</h2></div><span>Minsta sample size styr om procenttal visas</span></header>
      {runs?.length ? <div className={styles.grid}>{runs.map((run: any) => <article key={run.id}><small>{asset(run.assets)} · {run.strategy_definitions?.timeframe} · v{run.strategy_definitions?.version}</small><h3>{run.strategy_definitions?.name}</h3><div className={styles.metrics}><Metric label="Status" value={run.status}/><Metric label="Samples" value={`${run.sample_size}/${run.minimum_sample_size}`}/><Metric label="Win rate" value={metric(run.metrics?.winRate, "%")}/><Metric label="Profit factor" value={metric(run.metrics?.profitFactor)}/><Metric label="Average R" value={metric(run.metrics?.averageR)}/><Metric label="Max DD (R)" value={metric(run.metrics?.maxDrawdownR)}/></div><footer>Cutoff {new Date(run.information_cutoff_at).toLocaleString("sv-SE")} · candles {run.candle_count} · setups {run.setup_count} · trades {run.trade_count}</footer></article>)}</div> : <div className={styles.empty}><strong>INSUFFICIENT DATA</strong><span>Inga historiska candle-dataset har utvärderats ännu. Systemet visar inte påhittade resultat.</span></div>}
    </section>
  </main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><strong>{value}</strong></div>; }
function Rule({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function metric(value: unknown, suffix = "") { const number = Number(value); return value === null || value === undefined || !Number.isFinite(number) ? "INSUFFICIENT DATA" : `${number.toFixed(2)}${suffix}`; }
function asset(value: any) { return Array.isArray(value) ? value[0]?.symbol ?? "UNKNOWN" : value?.symbol ?? "UNKNOWN"; }
