import { randomUUID } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { EventEnvelope } from "@/domain/events";
import { deterministicDigest } from "@/domain/events";
import { evaluateFastFlow, findVerifiedConvergence, FAST_FLOW_POLICY, measureFastFlowLatency, type FastSafetyEvidence, type IndependenceEvidence, type VerifiedBuy } from "@/domain/fast-flow";
import { OPPORTUNITY_POLICY_VERSION } from "@/domain/opportunities";
import { EvidenceRepository } from "@/services/evidence/repository";
import { OpportunityRepository } from "@/services/opportunities/repository";

export class FastFlowService {
  private readonly evidence:EvidenceRepository; private readonly opportunities:OpportunityRepository;
  constructor(private readonly db:SupabaseClient){this.evidence=new EvidenceRepository(db);this.opportunities=new OpportunityRepository(db);}
  async handle(event:EventEnvelope){if(event.eventType!=="wallet.buy_detected"||!event.assetId)return {status:"ignored" as const}; const now=new Date().toISOString();
    const {data:existing,error:existingError}=await this.db.from("opportunity_revisions").select("opportunity_id,state").eq("trigger_event_id",event.eventId).eq("revision_type","v0_fast_safety").limit(1).maybeSingle();if(existingError)throw existingError;if(existing)return{status:"already_evaluated" as const,opportunityId:existing.opportunity_id,state:existing.state};
    const buys=await this.verifiedBuys(event.assetId,event.occurredAt,now); const cluster=findVerifiedConvergence(buys).find(items=>items.some(item=>item.eventId===event.eventId)); if(!cluster)return {status:"no_convergence" as const};
    const independence=await this.independence(cluster,now); const safety=await this.safety(event.assetId,now); const evaluation=evaluateFastFlow(cluster,independence,safety);
    const source=cluster[0]; const opportunityId=await this.opportunities.create({opportunityId:randomUUID(),assetId:event.assetId,opportunityType:"fast_flow",detectedAt:now,createdFromEventId:source.eventId,policyVersion:FAST_FLOW_POLICY.version});
    const {data:aggregate,error}=await this.db.from("opportunities").select("current_state,current_revision").eq("id",opportunityId).single(); if(error)throw error;
    const refs=await this.evidenceRefs(evaluation.evidenceIds); await this.opportunities.appendRevision({opportunityId,revisionNumber:Number(aggregate.current_revision)+1,revisionType:"v0_fast_safety",currentState:aggregate.current_state,nextState:evaluation.state,
      createdAt:now,informationCutoffAt:now,triggerEventId:event.eventId,evidenceRefs:refs,agentOutputs:{fastFlow:{walletIds:evaluation.walletIds,eventIds:evaluation.eventIds,windowSeconds:FAST_FLOW_POLICY.windowSeconds,rawWalletCount:evaluation.walletIds.length,relationshipCoverage:independence.relationshipCoverage??null,confirmedIndependentCount:independence.confirmedIndependentCount??null,clusterAdjustedCount:independence.clusterAdjustedCount??null,latency:measureFastFlowLatency(cluster,now)}},safetyResult:evaluation.safetyResult,
      opportunityScore:evaluation.opportunityScore,riskScore:evaluation.riskScore,dataQuality:evaluation.dataQuality}); return {status:"evaluated" as const,opportunityId,state:evaluation.state}; }

  private async verifiedBuys(assetId:string,occurredAt:string,cutoff:string){const radius=FAST_FLOW_POLICY.windowSeconds*1000;const from=new Date(new Date(occurredAt).getTime()-radius).toISOString(),to=new Date(new Date(occurredAt).getTime()+radius).toISOString();
    const {data:events,error}=await this.db.from("event_outbox").select("event_id,wallet_id,occurred_at,available_at,payload_hash,payload").eq("event_type","wallet.buy_detected").eq("asset_id",assetId).gte("occurred_at",from).lte("occurred_at",to).lte("available_at",cutoff).order("occurred_at");if(error)throw error;
    const walletIds=[...new Set((events??[]).map(item=>item.wallet_id).filter(Boolean))];const {data:checks,error:checkError}=walletIds.length?await this.db.from("wallet_verification_evaluations").select("id,wallet_id,eligible_status,evaluated_at,data_snapshot_cutoff,evidence").in("wallet_id",walletIds).eq("eligible_status","verified").lte("evaluated_at",cutoff).order("evaluated_at",{ascending:false}):{data:[],error:null};if(checkError)throw checkError;
    const latest=new Map<string,any>();for(const check of checks??[])if(!latest.has(check.wallet_id))latest.set(check.wallet_id,check);const output:VerifiedBuy[]=[];
    for(const row of events??[]){const check=latest.get(row.wallet_id);if(!check)continue;const eventRef=await this.evidence.register({evidenceType:"wallet_buy_event",sourceTable:"event_outbox",sourceRecordId:row.event_id,availableAt:row.available_at,payloadHash:row.payload_hash});const verifyRef=await this.evidence.register({evidenceType:"wallet_verification",sourceTable:"wallet_verification_evaluations",sourceRecordId:check.id,availableAt:check.evaluated_at,payloadHash:deterministicDigest(check)});
      output.push({eventId:row.event_id,eventEvidenceId:eventRef.evidenceId,assetId,walletId:row.wallet_id,occurredAt:row.occurred_at,availableAt:row.available_at,verificationEvidenceId:verifyRef.evidenceId,dataQuality:Number(check.evidence?.dataQualityV3??100)}); }
    return output; }
  private async independence(cluster:VerifiedBuy[],cutoff:string):Promise<IndependenceEvidence>{const ids=cluster.map(item=>item.walletId);const{data:snapshots,error}=await this.db.from("wallet_cluster_snapshots").select("*").lte("information_cutoff_at",cutoff).lte("available_at",cutoff).order("information_cutoff_at",{ascending:false}).limit(20);if(error)throw error;if(!snapshots?.length)return{status:"unknown",evidenceIds:[],relationshipTypes:[],dataQuality:0,clusterAdjustedCount:null};const snapshotIds=snapshots.map(row=>row.id);const{data:members,error:mError}=await this.db.from("wallet_cluster_memberships").select("*").in("snapshot_id",snapshotIds).in("wallet_id",ids);if(mError)throw mError;const snapshot=snapshots.find(row=>new Set((members??[]).filter(item=>item.snapshot_id===row.id).map(item=>item.wallet_id)).size===ids.length);if(!snapshot)return{status:"unknown",evidenceIds:[],relationshipTypes:[],dataQuality:0,clusterAdjustedCount:null};const selected=(members??[]).filter(item=>item.snapshot_id===snapshot.id);const refs=[await this.evidence.register({evidenceType:"wallet_cluster_snapshot",sourceTable:"wallet_cluster_snapshots",sourceRecordId:snapshot.id,availableAt:snapshot.available_at,payloadHash:deterministicDigest(snapshot)})];for(const row of selected)refs.push(await this.evidence.register({evidenceType:"wallet_cluster_membership",sourceTable:"wallet_cluster_memberships",sourceRecordId:`${row.snapshot_id}:${row.wallet_id}`,availableAt:snapshot.available_at,payloadHash:deterministicDigest(row)}));const evidenceIds=refs.map(ref=>ref.evidenceId);if(snapshot.status!=="available"||selected.some(item=>item.relationship_status==="unknown"))return{status:"unknown",evidenceIds,relationshipTypes:[],dataQuality:Number(snapshot.data_quality),relationshipCoverage:Number(snapshot.relationship_coverage),clusterAdjustedCount:null,modelVersion:snapshot.model_version,cutoff:snapshot.information_cutoff_at};const groups=new Map<string,any[]>();for(const row of selected){const key=row.cluster_id??`wallet:${row.wallet_id}`;groups.set(key,[...(groups.get(key)??[]),row]);}const related=[...groups.values()].filter(group=>group.length>1);const adjusted=[...groups.values()].reduce((sum,group)=>group.length===1?sum+1:sum+1+(group.length-1)*(1-Math.max(...group.map(item=>Number(item.cluster_confidence??0)))/100),0);return{status:related.length?"related":"confirmed",evidenceIds,relationshipTypes:related.length?["clustered"]:[],dataQuality:Number(snapshot.data_quality),relationshipCoverage:Number(snapshot.relationship_coverage),confirmedIndependentCount:groups.size,clusterAdjustedCount:Math.round(adjusted*100)/100,modelVersion:snapshot.model_version,cutoff:snapshot.information_cutoff_at};}
  private async safety(assetId:string,cutoff:string):Promise<FastSafetyEvidence>{const [{data:liquidity,error:lError},{data:risk,error:rError}]=await Promise.all([this.db.from("crypto_liquidity_snapshots").select("*").eq("asset_id",assetId).lte("information_available_at",cutoff).order("information_available_at",{ascending:false}).limit(1).maybeSingle(),this.db.from("token_risk_assessments").select("*").eq("asset_id",assetId).lte("information_available_at",cutoff).order("information_available_at",{ascending:false}).limit(1).maybeSingle()]);if(lError)throw lError;if(rError)throw rError;
    let liquidityEvidenceId:string|null=null,riskEvidenceId:string|null=null;if(liquidity){liquidityEvidenceId=(await this.evidence.register({evidenceType:"liquidity_snapshot",sourceTable:"crypto_liquidity_snapshots",sourceRecordId:liquidity.id,availableAt:liquidity.information_available_at,payloadHash:deterministicDigest(liquidity)})).evidenceId;}if(risk){riskEvidenceId=(await this.evidence.register({evidenceType:"token_risk",sourceTable:"token_risk_assessments",sourceRecordId:risk.id,availableAt:risk.information_available_at,payloadHash:deterministicDigest(risk)})).evidenceId;}
    const components=Array.isArray(risk?.risk_components?.components)?risk.risk_components.components:[];const knownAuthorities=["mint_authority","freeze_authority"].every(key=>components.some((item:any)=>item.key===key&&item.status!=="unknown"));return{liquidityUsd:liquidity?Number(liquidity.liquidity_usd):null,liquidityQuality:liquidity?Number(liquidity.data_quality):0,liquidityEvidenceId,riskStatus:risk?.rug_status??"UNKNOWN",riskQuality:risk?Number(risk.data_quality):0,riskEvidenceId,authorityCoverage:knownAuthorities?"complete":components.length?"partial":"unknown"};}
  private async evidenceRefs(ids:string[]){if(!ids.length)return[];const {data,error}=await this.db.from("evidence_records").select("evidence_id,evidence_type,available_at,payload_hash").in("evidence_id",ids);if(error)throw error;return(data??[]).map(row=>({evidenceId:row.evidence_id,evidenceType:row.evidence_type,availableAt:row.available_at,payloadHash:row.payload_hash}));}
}
