export type SystemKind =
  "DATA" | "ON_CHAIN" | "DECISION" | "RESEARCH" | "PORTFOLIO" | "INTELLIGENCE";
export interface SystemCatalogItem {
  name: string;
  kind: SystemKind;
  backendJob: string | null;
  schedulerType: string | null;
  frontend: string;
  route: string;
  description: string;
}

export const SYSTEM_CATALOG: SystemCatalogItem[] = [
  {
    name: "Stock Quotes",
    kind: "DATA",
    backendJob: "stock_quotes",
    schedulerType: "STOCK_INGESTION",
    frontend: "Watchlist",
    route: "/watchlist",
    description: "Finnhub snapshots persisted in Supabase.",
  },
  {
    name: "Historical Candles",
    kind: "DATA",
    backendJob: "candle_ingestion",
    schedulerType: "CANDLE_INGESTION",
    frontend: "Strategy Lab",
    route: "/strategy-lab",
    description: "Point-in-time OHLCV for technical research.",
  },
  {
    name: "Crypto Market",
    kind: "DATA",
    backendJob: "crypto_market",
    schedulerType: "CRYPTO_MARKET",
    frontend: "Market Radar",
    route: "/",
    description: "DEX price, pool and liquidity observations.",
  },
  {
    name: "Wallet Transactions",
    kind: "ON_CHAIN",
    backendJob: "wallet_transactions",
    schedulerType: "WALLET_INGESTION",
    frontend: "Agent Center",
    route: "/agents",
    description: "Normalized Solana activity with signature idempotency.",
  },
  {
    name: "Wallet Discovery",
    kind: "ON_CHAIN",
    backendJob: "wallet_discovery",
    schedulerType: "WALLET_DISCOVERY",
    frontend: "Market Radar",
    route: "/",
    description: "Candidate wallet discovery and quality evidence.",
  },
  {
    name: "Wallet Promotion",
    kind: "ON_CHAIN",
    backendJob: "wallet_promotion",
    schedulerType: "WALLET_PROMOTION",
    frontend: "Data Operations",
    route: "/data-collection",
    description:
      "Deterministic candidate-to-tracked promotion with immutable blockers.",
  },
  {
    name: "Wallet PnL",
    kind: "ON_CHAIN",
    backendJob: "wallet_pnl",
    schedulerType: null,
    frontend: "Agent Center",
    route: "/agents",
    description: "Historical wallet performance observations.",
  },
  {
    name: "Wallet Evidence",
    kind: "ON_CHAIN",
    backendJob: "wallet_evidence",
    schedulerType: null,
    frontend: "Agent Center",
    route: "/agents",
    description: "Liquidity and token-risk coverage for wallet trades.",
  },
  {
    name: "Wallet Clustering",
    kind: "ON_CHAIN",
    backendJob: "wallet_clustering",
    schedulerType: null,
    frontend: "Fast Flow",
    route: "/fast-flow",
    description: "Funding relations, clusters and independence.",
  },
  {
    name: "Fast Flow",
    kind: "DECISION",
    backendJob: "fast_flow",
    schedulerType: null,
    frontend: "Fast Flow",
    route: "/fast-flow",
    description: "Verified convergence with hard safety checks.",
  },
  {
    name: "Jackpot Collector",
    kind: "DECISION",
    backendJob: "jackpot_collector",
    schedulerType: null,
    frontend: "Jackpot Radar",
    route: "/jackpot",
    description: "Immutable early-candidate evidence timelines.",
  },
  {
    name: "Market Event Producers",
    kind: "DECISION",
    backendJob: "market_events",
    schedulerType: null,
    frontend: "Jackpot Radar",
    route: "/jackpot",
    description: "Deterministic market observation events.",
  },
  {
    name: "Qualification Diagnostics",
    kind: "DECISION",
    backendJob: "qualification",
    schedulerType: null,
    frontend: "Jackpot Radar",
    route: "/jackpot",
    description: "PASS, FAIL and UNKNOWN requirements with blockers.",
  },
  {
    name: "Data Gap Closure",
    kind: "DECISION",
    backendJob: "data_gap_closure",
    schedulerType: null,
    frontend: "Data Collection",
    route: "/data-collection",
    description: "Attempts to replace UNKNOWN with verified evidence.",
  },
  {
    name: "Paper Portfolio",
    kind: "PORTFOLIO",
    backendJob: "paper_execution",
    schedulerType: null,
    frontend: "Paper Portfolio",
    route: "/paper",
    description: "Deterministic hypothetical orders and fills.",
  },
  {
    name: "Portfolio Performance",
    kind: "PORTFOLIO",
    backendJob: "performance",
    schedulerType: null,
    frontend: "Paper Portfolio",
    route: "/paper",
    description: "Funnel, PnL, drawdown and policy behavior.",
  },
  {
    name: "Execution Infrastructure",
    kind: "PORTFOLIO",
    backendJob: "execution",
    schedulerType: null,
    frontend: "Execution Guard",
    route: "/execution",
    description:
      "Immutable intents, deterministic safety, shadow orders and provider reconciliation. Live execution is disabled.",
  },
  {
    name: "Trade Eligibility",
    kind: "DECISION",
    backendJob: "trade_eligibility",
    schedulerType: null,
    frontend: "Execution Guard",
    route: "/execution",
    description:
      "Deterministic PASS, FAIL and UNKNOWN gate between policy proposals and execution intents.",
  },
  {
    name: "Trade Proposal Producer",
    kind: "DECISION",
    backendJob: "trade_proposal_producer",
    schedulerType: null,
    frontend: "Execution Guard",
    route: "/execution",
    description:
      "Creates immutable spot proposals from qualified opportunities, Meta readiness and point-in-time evidence.",
  },
  {
    name: "Execution Pipeline",
    kind: "PORTFOLIO",
    backendJob: "execution_pipeline",
    schedulerType: "EXECUTION_PIPELINE",
    frontend: "Execution Guard",
    route: "/execution",
    description:
      "Leased one-minute orchestration through every deterministic gate; shadow/demo only.",
  },
  {
    name: "Historical FX",
    kind: "PORTFOLIO",
    backendJob: "fx",
    schedulerType: null,
    frontend: "Simulation Lab",
    route: "/simulation",
    description: "Point-in-time currency conversion without fixed fallback.",
  },
  {
    name: "Simulation Engine",
    kind: "RESEARCH",
    backendJob: "simulation",
    schedulerType: null,
    frontend: "Simulation Lab",
    route: "/simulation",
    description: "Capital replay with fees, slippage and liquidity.",
  },
  {
    name: "Historical Replay",
    kind: "RESEARCH",
    backendJob: "historical_replay",
    schedulerType: null,
    frontend: "Historical Replay",
    route: "/replay",
    description: "Rebuilds the information state at historical time T.",
  },
  {
    name: "Technical Structure",
    kind: "RESEARCH",
    backendJob: "specialist_agents",
    schedulerType: "SPECIALIST_AGENTS",
    frontend: "Strategy Lab",
    route: "/strategy-lab",
    description: "Deterministic price structure and technical context.",
  },
  {
    name: "Strategy Pattern Lab",
    kind: "RESEARCH",
    backendJob: "strategy_pattern_lab",
    schedulerType: null,
    frontend: "Strategy Lab",
    route: "/strategy-lab",
    description: "Immutable strategy definitions and replay evaluations.",
  },
  {
    name: "Expert Knowledge",
    kind: "INTELLIGENCE",
    backendJob: "expert_knowledge",
    schedulerType: null,
    frontend: "Expert Knowledge",
    route: "/knowledge",
    description: "Versioned rules, sources and retrieval traces.",
  },
  {
    name: "News Ingestion",
    kind: "INTELLIGENCE",
    backendJob: "news_ingestion",
    schedulerType: "NEWS_INGESTION",
    frontend: "Forecasts",
    route: "/forecasts",
    description: "Verified news observations and source classification.",
  },
  {
    name: "Catalyst Classification",
    kind: "INTELLIGENCE",
    backendJob: "catalyst_classification",
    schedulerType: "CATALYST_CLASSIFICATION",
    frontend: "Forecasts",
    route: "/forecasts",
    description: "Deterministic event type, facts and watch lifecycle.",
  },
  {
    name: "Specialist Agents",
    kind: "INTELLIGENCE",
    backendJob: "specialist_agents",
    schedulerType: "SPECIALIST_AGENTS",
    frontend: "Agent Center",
    route: "/agents",
    description: "Traceable specialist opinions over structured evidence.",
  },
  {
    name: "Consensus Engine",
    kind: "INTELLIGENCE",
    backendJob: "consensus",
    schedulerType: "CONSENSUS",
    frontend: "Agent Center",
    route: "/agents",
    description: "Conflict and evidence-independence analysis.",
  },
  {
    name: "Agent Performance",
    kind: "INTELLIGENCE",
    backendJob: "agent_performance",
    schedulerType: "AGENT_PERFORMANCE",
    frontend: "Agent Center",
    route: "/agents",
    description: "Measured independent and incremental agent edge.",
  },
  {
    name: "Market Regime",
    kind: "INTELLIGENCE",
    backendJob: "market_regime",
    schedulerType: "MARKET_REGIME",
    frontend: "Agent Center",
    route: "/agents",
    description: "Point-in-time deterministic regime context.",
  },
  {
    name: "Meta Agent",
    kind: "INTELLIGENCE",
    backendJob: "meta_agent",
    schedulerType: "META_AGENT",
    frontend: "Agent Center",
    route: "/agents",
    description: "Policy readiness synthesis; never execution.",
  },
  {
    name: "Baseline Forecast",
    kind: "INTELLIGENCE",
    backendJob: "baseline_forecast",
    schedulerType: "BASELINE_FORECAST",
    frontend: "Forecasts",
    route: "/forecasts",
    description: "Empirical baseline forecasts with insufficient-data states.",
  },
  {
    name: "Forecast Outcomes",
    kind: "INTELLIGENCE",
    backendJob: "forecast_outcomes",
    schedulerType: "FORECAST_OUTCOME",
    frontend: "Forecasts",
    route: "/forecasts",
    description: "Outcome completion after each forecast horizon.",
  },
  {
    name: "Forecast Calibration",
    kind: "INTELLIGENCE",
    backendJob: "forecast_performance",
    schedulerType: "FORECAST_PERFORMANCE",
    frontend: "Forecasts",
    route: "/forecasts",
    description: "Performance and probability calibration snapshots.",
  },
];
