import type{SupabaseClient}from"@supabase/supabase-js";import{buildGapClosure,DATA_GAP_CLOSURE_VERSION,type GapEvidence}from"@/domain/data-gap-closure";import type{HistoricalLiquidityProvider}from"@/services/liquidity/provider";import type{TokenRiskProvider}from"@/services/token-risk/provider";import type{IngestionRepository}from"@/repositories/ingestion-repository";
export class DataGapClosureService{constructor(private db:SupabaseClient,private liquidity:HistoricalLiquidityProvider,private risk:TokenRiskProvider,private repo:IngestionRepository){}
async run(limit=4,cutoff=new Date().toISOString()){const{data,error}=await this.db.from("jackpot_candidates").select("*,assets(external_id,crypto_tokens(mint_address,first_seen_at)),jackpot_candidate_revisions(*)").not("current_state","in",'(REJECTED,EXPIRED)').order("detected_at",{ascending:false}).limit(Math.max(1,Math.min(limit,20)));if(error)throw error;let created=0;const summaries=[];for(const c of data??[]){const result=await this.closeCandidate(c,cutoff);if(result.created)created++;summaries.push(result)}return{candidates:(data??[]).length,created,summaries}}
private async closeCandidate(c:any,cutoff:string){const revisions=[...(c.jackpot_candidate_revisions??[])].sort((a:any,b:any)=>a.revision_number-b.revision_number),source=revisions.at(-1);if(!source)return{candidateId:c.id,created:false,gaps:{},errors:["NO_SOURCE_REVISION"]};const asset=Array.isArray(c.assets)?c.assets[0]:c.assets,token=Array.isArray(asset?.crypto_tokens)?asset.crypto_tokens[0]:asset?.crypto_tokens,mint=token?.mint_address??asset?.external_id;const errors:string[]=[];
let liquidity=await this.storedLiquidity(c.asset_id,cutoff);if(!liquidity&&mint){try{const from=new Date(Math.max(Date.parse(c.detected_at),Date.parse(cutoff)-86_400_000)).toISOString(),points=await this.liquidity.getHistoricalLiquidity({assetId:c.asset_id,mintAddress:mint,from,to:cutoff,informationCutoffAt:cutoff});await this.repo.saveLiquiditySnapshots(points);liquidity=await this.storedLiquidity(c.asset_id,cutoff)}catch(e){errors.push(`LIQUIDITY:${message(e)}`)}}
let risk=await this.storedRisk(c.asset_id,cutoff);if(!risk&&mint){try{await this.repo.saveTokenRiskAssessment(c.asset_id,await this.risk.assess(mint,cutoff));risk=await this.storedRisk(c.asset_id,cutoff)}catch(e){errors.push(`RISK:${message(e)}`)}}
const verified=await this.verifiedWallets(c.asset_id,cutoff),events=await this.acceleration(c.asset_id,cutoff),tokenAge=token?.first_seen_at?Math.max(0,Math.floor((Date.parse(cutoff)-Date.parse(token.first_seen_at))/3_600_000)*3_600):null;
const closure=buildGapClosure({candidateId:c.id,candidateRevision:source.revision_number,cutoff,previousFeatures:source.features??{},liquidity:liquidity?{value:Number(liquidity.liquidity_usd),evidence:ref("liquidity_snapshot",liquidity.id,liquidity.information_available_at,liquidity.provider,liquidity.data_quality)}:null,risk:risk?{status:risk.rug_status,coverage:riskCoverage(risk.risk_components),evidence:ref("token_risk_assessment",risk.id,risk.information_available_at,risk.provider,risk.data_quality)}:null,verifiedWalletCount:verified.count,tokenAgeSeconds:tokenAge,priceAcceleration:events.price,volumeAcceleration:events.volume});
const existing=await this.db.from("candidate_data_gap_evaluations").select("id").eq("closure_hash",closure.closureHash).maybeSingle();if(existing.error)throw existing.error;if(existing.data)return{candidateId:c.id,created:false,gaps:closure.gaps,errors};const next=Number(c.current_revision)+1,safety=closure.features.riskStatus==="CONFIRMED_RUG"||closure.features.riskStatus==="HIGH_RISK"?"FAIL":closure.features.riskStatus==="UNKNOWN"?"UNKNOWN":"PASS",revisionHash=closure.closureHash;
const saved=await this.db.from("jackpot_candidate_revisions").insert({candidate_id:c.id,revision_number:next,revision_type:"v3_risk_liquidity",state:c.current_state,trigger_event_id:null,information_cutoff_at:cutoff,available_at:cutoff,features:closure.features,probability_features:source.probability_features??{},payoff_features:{...(source.payoff_features??{}),liquidity:closure.features.liquidity,tokenAgeSeconds:closure.features.tokenAgeSeconds},safety_result:{status:safety,riskStatus:closure.features.riskStatus},evidence_refs:closure.evidence,revision_hash:revisionHash});if(saved.error)throw saved.error;const updated=await this.db.from("jackpot_candidates").update({current_revision:next}).eq("id",c.id).eq("current_revision",c.current_revision);if(updated.error)throw updated.error;const evaluation=await this.db.from("candidate_data_gap_evaluations").insert({candidate_id:c.id,source_revision:source.revision_number,result_revision:next,candidate_cutoff_at:source.information_cutoff_at,evaluated_at:cutoff,closure_version:DATA_GAP_CLOSURE_VERSION,gap_statuses:closure.gaps,evidence_refs:closure.evidence,provider_errors:errors,closure_hash:closure.closureHash});if(evaluation.error)throw evaluation.error;return{candidateId:c.id,created:true,revision:next,gaps:closure.gaps,errors}}
private async storedLiquidity(assetId:string,cutoff:string){const{data,error}=await this.db.from("crypto_liquidity_snapshots").select("id,liquidity_usd,information_available_at,provider,data_quality,effective_at").eq("asset_id",assetId).lte("information_available_at",cutoff).lte("effective_at",cutoff).order("effective_at",{ascending:false}).order("liquidity_usd",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data}
private async storedRisk(assetId:string,cutoff:string){const{data,error}=await this.db.from("token_risk_assessments").select("id,rug_status,risk_components,information_available_at,provider,data_quality").eq("asset_id",assetId).lte("information_available_at",cutoff).order("information_available_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data}
private async verifiedWallets(assetId:string,cutoff:string){const{data:tx,error}=await this.db.from("wallet_transactions").select("wallet_id").eq("asset_id",assetId).eq("side","buy").lte("ingested_at",cutoff);if(error)throw error;const ids=[...new Set((tx??[]).map((x:any)=>x.wallet_id))];if(!ids.length)return{count:null};const{data,error:e}=await this.db.from("wallet_verification_evaluations").select("wallet_id,eligible_status,evaluated_at").in("wallet_id",ids).lte("evaluated_at",cutoff).order("evaluated_at",{ascending:false});if(e)throw e;const latest=new Map<string,string>();for(const row of data??[])if(!latest.has(row.wallet_id))latest.set(row.wallet_id,row.eligible_status);if(latest.size<ids.length)return{count:null};return{count:[...latest.values()].filter(x=>x==="verified").length}}
private async acceleration(assetId:string,cutoff:string){const{data,error}=await this.db.from("event_outbox").select("event_id,event_type,available_at,provider,data_quality").eq("asset_id",assetId).in("event_type",["market.price_accelerated","market.volume_accelerated"]).lte("available_at",cutoff).order("available_at",{ascending:false});if(error)throw error;const find=(type:string)=>{const x=(data??[]).find((e:any)=>e.event_type===type);return x?ref("event",x.event_id,x.available_at,x.provider,x.data_quality):null};return{price:find("market.price_accelerated"),volume:find("market.volume_accelerated")}}
}
function ref(type:string,id:string,availableAt:string,source:string,quality:number|null):GapEvidence{return{id,type,availableAt,source,dataQuality:quality}}
function riskCoverage(value:any){const c=value?.components;return Array.isArray(c)&&c.length?Math.round(c.filter((x:any)=>x.status&&x.status!=="unknown"&&x.status!=="UNKNOWN").length/c.length*100):0}
function message(e:unknown){return e instanceof Error?e.message:String(e)}
