import type{SupabaseClient}from"@supabase/supabase-js";import type{SourceClassification,WalletRelationshipFeature}from"@/domain/wallet-clustering";import type{WalletRelationshipDataProvider}from"./provider";
type Raw={transaction?:{message?:{accountKeys?:Array<string|{pubkey?:string}>}};meta?:{preBalances?:number[];postBalances?:number[]}};
export class SupabaseWalletRelationshipProvider implements WalletRelationshipDataProvider{readonly name="supabase-solana-history-v1";constructor(private db:SupabaseClient){}
  async loadFeatures(cutoff:string,limit:number){const{data:wallets,error}=await this.db.from("wallets").select("id,address,first_seen_at").eq("chain","solana").eq("is_tracked",true).order("created_at").limit(limit);if(error)throw error;if(!wallets?.length)return[];const ids=wallets.map(x=>x.id);
    const[{data:tx,error:txError},{data:verification,error:vError},{data:labels,error:lError}]=await Promise.all([this.db.from("wallet_transactions").select("wallet_id,asset_id,side,occurred_at,ingested_at,raw_payload").in("wallet_id",ids).lte("ingested_at",cutoff).order("occurred_at").limit(Math.max(1000,limit*500)),this.db.from("wallet_verification_evaluations").select("wallet_id,eligible_status,evaluated_at,evidence").in("wallet_id",ids).lte("evaluated_at",cutoff).order("evaluated_at",{ascending:false}),this.db.from("solana_address_classification_observations").select("address,classification,confidence,available_at").lte("available_at",cutoff).order("available_at",{ascending:false})]);if(txError)throw txError;if(vError)throw vError;if(lError)throw lError;
    const labelMap=new Map<string,SourceClassification>();for(const row of labels??[])if(!labelMap.has(row.address)&&Number(row.confidence)>=80)labelMap.set(row.address,row.classification);const latest=new Map<string,any>();for(const row of verification??[])if(!latest.has(row.wallet_id))latest.set(row.wallet_id,row);
    return wallets.map(wallet=>{const rows=(tx??[]).filter(row=>row.wallet_id===wallet.id),check=latest.get(wallet.id),funding=findFunding(rows,wallet.address),counterparties=[...new Set(rows.flatMap(row=>accounts(row.raw_payload)).filter(address=>address!==wallet.address&&!isService(address,labelMap)))];const trades:Record<string,string[]>={};for(const row of rows)if(row.asset_id&&["buy","sell"].includes(row.side))(trades[row.asset_id]??=[]).push(row.occurred_at);return{walletId:wallet.id,dataQuality:Number(check?.evidence?.dataQualityV3??0),historyComplete:check?.eligible_status==="verified",firstSeenAt:wallet.first_seen_at??rows[0]?.occurred_at??null,firstFundingAt:funding?.occurredAt??null,funderAddress:funding?.address??null,fundingSourceClassification:funding?labelMap.get(funding.address)??"unknown":"unknown",counterparties,tradeTimesByAsset:trades} satisfies WalletRelationshipFeature;});}}
function accounts(raw:Raw){return(raw?.transaction?.message?.accountKeys??[]).map(key=>typeof key==="string"?key:key.pubkey).filter((x):x is string=>Boolean(x));}
function findFunding(rows:any[],walletAddress:string){for(const row of rows){const raw=row.raw_payload as Raw,keys=accounts(raw),index=keys.indexOf(walletAddress),pre=raw?.meta?.preBalances??[],post=raw?.meta?.postBalances??[];if(index<0||(post[index]??0)-(pre[index]??0)<=0)continue;let source:string|null=null,largest=0;for(let i=0;i<keys.length;i+=1){const delta=(post[i]??0)-(pre[i]??0);if(delta<largest){largest=delta;source=keys[i];}}if(source)return{address:source,occurredAt:row.occurred_at};}return null;}
function isService(address:string,labels:Map<string,SourceClassification>){return["program","exchange","bridge"].includes(labels.get(address)??"");}
