import { createServiceClient } from "@/lib/supabase/server";
import styles from "./execution.module.css";
export const dynamic="force-dynamic";
export default async function ExecutionPage(){
 const db=createServiceClient();const[{data:control},{data:intents},{data:orders},{data:events},{data:runs},{data:eligibility},{data:accounts},{data:risk},{data:observations},{data:bridge},{data:producer}]=await Promise.all([
  db.from("execution_controls").select("*").eq("control_key","global").maybeSingle(),db.from("execution_intents").select("id,instrument_id,side,order_type,quote_amount_sek,information_cutoff_at").order("created_at",{ascending:false}).limit(12),db.from("execution_orders").select("id,intent_id,current_state").order("updated_at",{ascending:false}).limit(12),db.from("execution_order_events").select("id,previous_state,next_state,reason,occurred_at").order("occurred_at",{ascending:false}).limit(16),db.from("execution_reconciliation_runs").select("status,orders_checked,mismatches,recovered,finished_at").order("finished_at",{ascending:false}).limit(1),db.from("trade_eligibility_evaluations").select("id,decision,requirements_failed,requirements_unknown,trade_proposals!inner(instrument_id,side)").order("created_at",{ascending:false}).limit(12),db.from("execution_accounts").select("id,account_key,provider_environment,initial_cash_sek").order("created_at").limit(4),db.from("risk_ledger_snapshots").select("account_id,status,cash_sek,realized_pnl_sek,reserved_exposure_sek,unknown_reasons,information_cutoff_at").order("information_cutoff_at",{ascending:false}).limit(1),db.from("account_state_observations").select("account_id,data_status,total_equity_usd,available_quote_usd,observed_at").order("observed_at",{ascending:false}).limit(1),db.from("execution_bridge_attempts").select("id,outcome,requirements,safety_requirements,created_at,trade_proposals!inner(instrument_id,side)").order("created_at",{ascending:false}).limit(12),db.from("trade_proposal_producer_evaluations").select("id,decision,requirements,policy_version,opportunities!inner(asset_id,assets!inner(symbol))").order("created_at",{ascending:false}).limit(12)]);
 const orderByIntent=new Map((orders??[]).map((x:any)=>[x.intent_id,x])),limits=(control?.limits??{}) as Record<string,unknown>,lastRun=runs?.[0],latestRisk=risk?.[0],latestObservation=observations?.[0],account=accounts?.find((x:any)=>x.id===latestRisk?.account_id)??accounts?.[0];
 const {data:pipelineJob}=await db.from("scheduled_jobs").select("status,last_successful_run_at,next_run_at,consecutive_failures,last_error,metrics").eq("job_key","execution-pipeline-1m").maybeSingle();
 return <main className={styles.page}>
  <section className={styles.hero}><div><small>EXECUTION INFRASTRUCTURE V1</small><h1>Execution Guard</h1><p>Deterministic safety boundary between research and any provider. Only shadow or demo mode is permitted.</p></div><div className={styles.lock}><span>LIVE EXECUTION</span><strong>DISABLED</strong><small>Hard database invariant</small></div></section>
  <section className={styles.metrics}><article><span>Mode</span><strong data-tone="safe">{control?.mode??"UNAVAILABLE"}</strong></article><article><span>Provider</span><strong>{control?.provider??"UNKNOWN"}</strong></article><article><span>Kill switch</span><strong data-tone={control?.kill_switch?"danger":"safe"}>{control?.kill_switch?"ACTIVE":"READY"}</strong></article><article><span>Max order</span><strong>{String(limits.maxOrderSek??"UNKNOWN")} SEK</strong></article></section>
  <section className={styles.grid}><Panel title="Capital truth" kicker="ACCOUNT STATE" status={latestObservation?.data_status??"NOT OBSERVED"}><div className={styles.reconcile}><Metric value={account?.provider_environment==="SHADOW"?money(account?.initial_cash_sek,"SEK"):money(latestObservation?.total_equity_usd,"USD")} label={account?.provider_environment==="SHADOW"?"declared shadow capital":"provider equity"}/><Metric value={money(latestObservation?.available_quote_usd,"USD")} label="available provider quote"/><Metric value={account?.account_key??"UNKNOWN"} label="account"/></div><p>{latestObservation?.observed_at?`Observed ${new Date(latestObservation.observed_at).toLocaleString("sv-SE")}`:"No provider account observation yet."}</p></Panel><Panel title="Daily limits" kicker="RISK LEDGER" status={latestRisk?.status??"NOT BUILT"}><div className={styles.reconcile}><Metric value={money(latestRisk?.cash_sek,"SEK")} label="available cash"/><Metric value={money(latestRisk?.reserved_exposure_sek,"SEK")} label="reserved exposure"/><Metric value={money(latestRisk?.realized_pnl_sek,"SEK")} label="realized daily PnL"/></div><p>{latestRisk?.unknown_reasons?.length?`Blocked: ${latestRisk.unknown_reasons.join(" · ")}`:"All ledger inputs are known at the latest cutoff."}</p></Panel></section>
  <section className={styles.grid}><Panel title="Policy gate" kicker="TRADE ELIGIBILITY" status={`${eligibility?.length??0} evaluations`}>{eligibility?.length?<div className={styles.rows}>{eligibility.map((item:any)=>{const proposal=one(item.trade_proposals);return <Row key={item.id} left={proposal?.instrument_id??"UNKNOWN INSTRUMENT"} sub={`${proposal?.side??"UNKNOWN"} · policy v1`} state={item.decision} detail={[...(item.requirements_failed??[]),...(item.requirements_unknown??[])].slice(0,2).join(" · ")||"All requirements passed"}/>})}</div>:<Empty text="No trade proposals have been evaluated. Meta outputs cannot bypass this gate."/>}</Panel><Panel title="Provider truth" kicker="RECONCILIATION" status={lastRun?.status??"NOT RUN"}><div className={styles.reconcile}><Metric value={lastRun?.orders_checked??0} label="orders checked"/><Metric value={lastRun?.mismatches??0} label="mismatches"/><Metric value={lastRun?.recovered??0} label="recovered"/></div><p>{lastRun?.finished_at?`Last run ${new Date(lastRun.finished_at).toLocaleString("sv-SE")}`:"Run the execution worker to create the first reconciliation snapshot."}</p></Panel></section>
  <Panel title="Eligibility → safety" kicker="EXECUTION BRIDGE" status={`${bridge?.length??0} attempts`}>{bridge?.length?<div className={styles.rows}>{bridge.map((item:any)=>{const proposal=one(item.trade_proposals),blocked=[...(item.requirements??[]),...(item.safety_requirements??[])].filter((x:any)=>x.status!=="PASS").map((x:any)=>x.code);return <Row key={item.id} left={proposal?.instrument_id??"UNKNOWN"} sub={`${proposal?.side??"UNKNOWN"} · immutable bridge`} state={item.outcome} detail={blocked.slice(0,3).join(" · ")||"Final safety passed"}/>})}</div>:<Empty text="No eligible proposal has reached the execution bridge."/>}</Panel>
  <Panel title="Execution intents" kicker="IMMUTABLE FLOW" status={`${intents?.length??0} recent`}>{intents?.length?<div className={styles.rows}>{intents.map((intent:any)=><Row key={intent.id} left={intent.instrument_id} sub={`${intent.side} · ${intent.order_type} · ${Number(intent.quote_amount_sek)} SEK`} state={orderByIntent.get(intent.id)?.current_state??"PROPOSED"} detail={new Date(intent.information_cutoff_at).toLocaleString("sv-SE")}/>)}</div>:<Empty text="No execution intents. Research outputs are not automatically tradable."/>}</Panel>
  <Panel title="State timeline" kicker="AUDIT TRAIL" status="Append only">{events?.length?<div className={styles.timeline}>{events.map((event:any)=><div key={event.id}><time>{new Date(event.occurred_at).toLocaleTimeString("sv-SE")}</time><strong>{event.previous_state??"CREATED"} → {event.next_state}</strong><span>{event.reason}</span></div>)}</div>:<Empty text="No state transitions yet."/>}</Panel>
  <Panel title="Proposal diagnostics" kicker="TRADE PROPOSAL PRODUCER" status={`${producer?.length??0} evaluations`}>{producer?.length?<div className={styles.rows}>{producer.map((item:any)=>{const opportunity=one(item.opportunities),asset=one(opportunity?.assets),blocked=(item.requirements??[]).filter((x:any)=>x.status!=="PASS"&&x.status!=="NOT_APPLICABLE").map((x:any)=>x.blockerCode);return <Row key={item.id} left={asset?.symbol??"UNKNOWN ASSET"} sub={`${item.policy_version} · immutable`} state={item.decision} detail={blocked.slice(0,3).join(" · ")||"Proposal requirements passed"}/>})}</div>:<Empty text="No qualified point-in-time setup has been evaluated into a proposal yet."/>}</Panel>
  <Panel title="Automatic pipeline" kicker="SCHEDULER · 1 MINUTE" status={pipelineJob?.status??"NOT REGISTERED"}><div className={styles.reconcile}><Metric value={pipelineJob?.last_successful_run_at?new Date(pipelineJob.last_successful_run_at).toLocaleTimeString("sv-SE"):"NEVER"} label="last scheduler success"/><Metric value={pipelineJob?.next_run_at?new Date(pipelineJob.next_run_at).toLocaleTimeString("sv-SE"):"UNKNOWN"} label="next scheduled run"/><Metric value={pipelineJob?.consecutive_failures??0} label="consecutive failures"/></div><p>{pipelineJob?.last_error??"One leased run passes through proposal, eligibility, account/risk, bridge and shadow execution."}</p></Panel>
 </main>
}
function Panel({title,kicker,status,children}:{title:string;kicker:string;status:string;children:React.ReactNode}){return <article className={styles.panel}><header><div><small>{kicker}</small><h2>{title}</h2></div><span>{status}</span></header>{children}</article>}
function Row({left,sub,state,detail}:{left:string;sub:string;state:string;detail:string}){return <div className={styles.row}><div><strong>{left}</strong><small>{sub}</small></div><div><b data-state={state}>{state}</b><small>{detail}</small></div></div>}
function one(value:any){return Array.isArray(value)?value[0]:value}
function money(value:unknown,currency:string){return value===null||value===undefined?"UNKNOWN":`${Number(value).toLocaleString("sv-SE",{maximumFractionDigits:2})} ${currency}`}
function Metric({value,label}:{value:unknown;label:string}){return <div><strong>{String(value)}</strong><span>{label}</span></div>}
function Empty({text}:{text:string}){return <div className={styles.empty}><strong>NO ACTIVITY</strong><p>{text}</p></div>}
