create table public.news_sources(id uuid primary key default gen_random_uuid(),source_key text not null unique,display_name text not null,domain text not null unique,source_classification text not null check(source_classification in('OFFICIAL_SOURCE','PRIMARY_MEDIA','REPUTABLE_SECONDARY','SOCIAL_VERIFIED','SOCIAL_UNVERIFIED','UNKNOWN')),trust_policy_version text not null,active boolean not null default true,effective_at timestamptz not null,available_at timestamptz not null,created_at timestamptz not null default now());
insert into public.news_sources(source_key,display_name,domain,source_classification,trust_policy_version,effective_at,available_at) values('sec-gov','SEC','sec.gov','OFFICIAL_SOURCE','news-source-trust-v1',now(),now()),('reuters','Reuters','reuters.com','PRIMARY_MEDIA','news-source-trust-v1',now(),now()),('ap','Associated Press','apnews.com','PRIMARY_MEDIA','news-source-trust-v1',now(),now()),('bloomberg','Bloomberg','bloomberg.com','PRIMARY_MEDIA','news-source-trust-v1',now(),now()),('ft','Financial Times','ft.com','PRIMARY_MEDIA','news-source-trust-v1',now(),now()),('wsj','Wall Street Journal','wsj.com','PRIMARY_MEDIA','news-source-trust-v1',now(),now()) on conflict(source_key)do nothing;
alter table public.news_observations add column canonical_url text,add column source_id uuid references public.news_sources(id),add column trust_policy_version text not null default'news-source-trust-v1';
create index news_observations_canonical_idx on public.news_observations(asset_id,canonical_url);
create table public.news_article_revisions(id uuid primary key default gen_random_uuid(),revision_key text not null unique,news_observation_id uuid not null references public.news_observations(id),revision_number integer not null,headline text not null,summary text,canonical_url text not null,content_hash text not null,occurred_at timestamptz not null,observed_at timestamptz not null,available_at timestamptz not null,provider text not null,provider_article_id text not null,source_id uuid references public.news_sources(id),source_classification text not null,evidence_refs jsonb not null default'[]',raw_payload jsonb not null default'{}',created_at timestamptz not null default now(),check(occurred_at<=observed_at and observed_at<=available_at),unique(news_observation_id,revision_number),unique(news_observation_id,content_hash));
create table public.news_entity_matches(id uuid primary key default gen_random_uuid(),news_revision_id uuid not null references public.news_article_revisions(id),entity_type text not null,entity_id uuid not null,match_method text not null check(match_method in('PROVIDER_SYMBOL','CANONICAL_IDENTIFIER','MANUAL_VERIFIED')),confidence integer not null check(confidence between 0 and 100),available_at timestamptz not null,match_version text not null,created_at timestamptz not null default now(),unique(news_revision_id,entity_type,entity_id,match_method));
create or replace function public.prevent_news_trust_mutation()returns trigger language plpgsql as $$begin raise exception'News trust history is immutable';end$$;create trigger news_revisions_immutable before update or delete on public.news_article_revisions for each row execute function public.prevent_news_trust_mutation();create trigger news_entity_matches_immutable before update or delete on public.news_entity_matches for each row execute function public.prevent_news_trust_mutation();
alter table public.news_sources enable row level security;alter table public.news_article_revisions enable row level security;alter table public.news_entity_matches enable row level security;create policy "public read news sources" on public.news_sources for select using(true);create policy "public read news revisions" on public.news_article_revisions for select using(true);create policy "public read news entity matches" on public.news_entity_matches for select using(true);grant select on public.news_sources,public.news_article_revisions,public.news_entity_matches to anon,authenticated;grant all on public.news_sources,public.news_article_revisions,public.news_entity_matches to service_role;
alter table public.scheduled_jobs drop constraint if exists scheduled_jobs_job_type_check;alter table public.scheduled_jobs add constraint scheduled_jobs_job_type_check check(job_type in('BASELINE_FORECAST','FORECAST_OUTCOME','FORECAST_PERFORMANCE','NEWS_INGESTION'));insert into public.scheduled_jobs(job_key,job_type,scheduler_version,interval_seconds,lease_seconds,status,next_run_at,rate_limit_budget)values('news-ingestion-5m','NEWS_INGESTION','forecast-scheduler-v1.1',300,240,'HEALTHY',now(),' {"finnhubRequests":5,"maxArticlesPerSymbol":50}')on conflict(job_key)do nothing;
