-- Ten deterministic research candidates. Priority is a research queue, not a profitability claim.
insert into public.strategy_definitions
  (strategy_key, version, name, market, timeframe, setup_type, definition, definition_hash, effective_at, available_at)
select
  item->>'strategy_key',
  (item->>'version')::integer,
  item->>'name',
  item->>'market',
  item->>'timeframe',
  item->>'setup_type',
  item->'definition',
  item->>'definition_hash',
  '2026-08-24T00:00:00Z'::timestamptz,
  '2026-08-24T00:00:00Z'::timestamptz
from jsonb_array_elements($strategies$
[
  {"strategy_key":"orb-retest-15m","version":1,"name":"Opening Range Breakout · 15m Retest","market":"US_STOCKS","timeframe":"5m","setup_type":"OPENING_RANGE_BREAKOUT","definition_hash":"a6e1aa8b36201308ffd3497ca9a259613cc17684934bac73703ae37cf159ac9d","definition":{"market":"US_STOCKS","timeframe":"5m","setupType":"OPENING_RANGE_BREAKOUT","exchangeTimeZone":"America/New_York","allowedSession":"REGULAR","sessionWindows":[{"session":"REGULAR","timeZone":"America/New_York","openMinute":570,"closeMinute":960}],"rejectionCloseInside":false,"stopBufferBps":5,"targetPolicy":"FIXED_R","targetR":2,"breakoutConfirmation":"CLOSE","requireRetest":true,"retestToleranceBps":10,"retestMaxCandles":6,"entryCutoffMinutes":60,"minimumBreakoutVolumeMultiple":1.5,"requireVwapConfirmation":true,"feeBps":1,"slippageBps":2,"minimumSampleSize":30,"strategyId":"orb-retest-15m","version":1,"name":"Opening Range Breakout · 15m Retest","openingRangeMinutes":15}},
  {"strategy_key":"orb-retest-5m","version":1,"name":"Opening Range Breakout · 5m Retest","market":"US_STOCKS","timeframe":"5m","setup_type":"OPENING_RANGE_BREAKOUT","definition_hash":"b30c1e2b642bdc40bee38e8179bcb7d19d6ce22ebcc6030f9b44e084a7a85289","definition":{"market":"US_STOCKS","timeframe":"5m","setupType":"OPENING_RANGE_BREAKOUT","exchangeTimeZone":"America/New_York","allowedSession":"REGULAR","sessionWindows":[{"session":"REGULAR","timeZone":"America/New_York","openMinute":570,"closeMinute":960}],"rejectionCloseInside":false,"stopBufferBps":5,"targetPolicy":"FIXED_R","targetR":2,"breakoutConfirmation":"CLOSE","requireRetest":true,"retestToleranceBps":10,"retestMaxCandles":6,"entryCutoffMinutes":60,"minimumBreakoutVolumeMultiple":1.5,"requireVwapConfirmation":true,"feeBps":1,"slippageBps":2,"minimumSampleSize":30,"strategyId":"orb-retest-5m","version":1,"name":"Opening Range Breakout · 5m Retest","openingRangeMinutes":5}},
  {"strategy_key":"ema-vwap-momentum","version":1,"name":"EMA 9/20 + VWAP Momentum","market":"GENERIC","timeframe":"5m","setup_type":"EMA_VWAP_MOMENTUM","definition_hash":"e2a4192002013b524125decfbb95d2066e280db95f4a5ef4d6fbde05d41c06fc","definition":{"strategyId":"ema-vwap-momentum","version":1,"name":"EMA 9/20 + VWAP Momentum","market":"GENERIC","timeframe":"5m","setupType":"EMA_VWAP_MOMENTUM","exchangeTimeZone":"America/New_York","allowedSession":"REGULAR","sessionWindows":[{"session":"REGULAR","timeZone":"America/New_York","openMinute":570,"closeMinute":960}],"rejectionCloseInside":false,"stopBufferBps":2,"targetPolicy":"FIXED_R","targetR":2,"fastEmaPeriod":9,"slowEmaPeriod":20,"feeBps":1,"slippageBps":2,"minimumSampleSize":30}},
  {"strategy_key":"asia-ny-sweep-reversal","version":1,"name":"Asia / New York High-Low Sweep Reversal","market":"XAUUSD","timeframe":"5m","setup_type":"SESSION_SWEEP_REVERSAL","definition_hash":"2bf7c563c3dc07acfc7ed0bb5c188ca6ba70f721afc09dba99df4eb8661dce37","definition":{"strategyId":"asia-ny-sweep-reversal","version":1,"name":"Asia / New York High-Low Sweep Reversal","market":"XAUUSD","timeframe":"5m","setupType":"SESSION_SWEEP_REVERSAL","exchangeTimeZone":"UTC","referenceSession":"NEW_YORK","allowedSession":"ASIA","sessionWindows":[{"session":"ASIA","timeZone":"Asia/Tokyo","openMinute":540,"closeMinute":1020},{"session":"NEW_YORK","timeZone":"America/New_York","openMinute":480,"closeMinute":1020}],"rejectionCloseInside":true,"stopBufferBps":2,"targetPolicy":"OPPOSITE_REFERENCE_LEVEL","feeBps":1,"slippageBps":2,"minimumSampleSize":30}},
  {"strategy_key":"orb-retest-30m","version":1,"name":"Opening Range Breakout · 30m Retest","market":"US_STOCKS","timeframe":"5m","setup_type":"OPENING_RANGE_BREAKOUT","definition_hash":"2a7a03bb847a4a1bb11843b5128304b436686c6725ea2235da5cb872a8cf18d0","definition":{"market":"US_STOCKS","timeframe":"5m","setupType":"OPENING_RANGE_BREAKOUT","exchangeTimeZone":"America/New_York","allowedSession":"REGULAR","sessionWindows":[{"session":"REGULAR","timeZone":"America/New_York","openMinute":570,"closeMinute":960}],"rejectionCloseInside":false,"stopBufferBps":5,"targetPolicy":"FIXED_R","targetR":2,"breakoutConfirmation":"CLOSE","requireRetest":true,"retestToleranceBps":10,"retestMaxCandles":6,"entryCutoffMinutes":120,"minimumBreakoutVolumeMultiple":1.5,"requireVwapConfirmation":true,"feeBps":1,"slippageBps":2,"minimumSampleSize":30,"strategyId":"orb-retest-30m","version":1,"name":"Opening Range Breakout · 30m Retest","openingRangeMinutes":30}},
  {"strategy_key":"orb-direct-15m","version":1,"name":"Opening Range Breakout · 15m Direct","market":"US_STOCKS","timeframe":"5m","setup_type":"OPENING_RANGE_BREAKOUT","definition_hash":"1500c28c752531ec6a76bfc9b568c5a02805ad308d0d612903640c3acbd15739","definition":{"market":"US_STOCKS","timeframe":"5m","setupType":"OPENING_RANGE_BREAKOUT","exchangeTimeZone":"America/New_York","allowedSession":"REGULAR","sessionWindows":[{"session":"REGULAR","timeZone":"America/New_York","openMinute":570,"closeMinute":960}],"rejectionCloseInside":false,"stopBufferBps":5,"targetPolicy":"FIXED_R","targetR":2,"breakoutConfirmation":"CLOSE","requireRetest":false,"retestToleranceBps":10,"retestMaxCandles":6,"entryCutoffMinutes":60,"minimumBreakoutVolumeMultiple":1.5,"requireVwapConfirmation":true,"feeBps":1,"slippageBps":2,"minimumSampleSize":30,"strategyId":"orb-direct-15m","version":1,"name":"Opening Range Breakout · 15m Direct","openingRangeMinutes":15}},
  {"strategy_key":"ema-vwap-fast","version":1,"name":"EMA 5/13 + VWAP Momentum","market":"GENERIC","timeframe":"5m","setup_type":"EMA_VWAP_MOMENTUM","definition_hash":"bf7af68f454c7db7affbcd4e457a57999d1e46765bbf330f750b064b21c7fd33","definition":{"strategyId":"ema-vwap-fast","version":1,"name":"EMA 5/13 + VWAP Momentum","market":"GENERIC","timeframe":"5m","setupType":"EMA_VWAP_MOMENTUM","exchangeTimeZone":"America/New_York","allowedSession":"REGULAR","sessionWindows":[{"session":"REGULAR","timeZone":"America/New_York","openMinute":570,"closeMinute":960}],"rejectionCloseInside":false,"stopBufferBps":2,"targetPolicy":"FIXED_R","targetR":2,"fastEmaPeriod":5,"slowEmaPeriod":13,"feeBps":1,"slippageBps":2,"minimumSampleSize":30}},
  {"strategy_key":"ema-vwap-slow","version":1,"name":"EMA 20/50 + VWAP Trend","market":"GENERIC","timeframe":"5m","setup_type":"EMA_VWAP_MOMENTUM","definition_hash":"49598aad6ac6571b09388e039a1663f201911486274e3bc6eb8605564b1d6bdb","definition":{"strategyId":"ema-vwap-slow","version":1,"name":"EMA 20/50 + VWAP Trend","market":"GENERIC","timeframe":"5m","setupType":"EMA_VWAP_MOMENTUM","exchangeTimeZone":"America/New_York","allowedSession":"REGULAR","sessionWindows":[{"session":"REGULAR","timeZone":"America/New_York","openMinute":570,"closeMinute":960}],"rejectionCloseInside":false,"stopBufferBps":2,"targetPolicy":"FIXED_R","targetR":2,"fastEmaPeriod":20,"slowEmaPeriod":50,"feeBps":1,"slippageBps":2,"minimumSampleSize":30}},
  {"strategy_key":"london-prior-ny-sweep","version":1,"name":"London / Prior New York Sweep Reversal","market":"XAUUSD","timeframe":"5m","setup_type":"SESSION_SWEEP_REVERSAL","definition_hash":"70bde568ac53b83aa84d52de964ff1ad19d88a79e8f888cda094773e9b41c0e8","definition":{"strategyId":"london-prior-ny-sweep","version":1,"name":"London / Prior New York Sweep Reversal","market":"XAUUSD","timeframe":"5m","setupType":"SESSION_SWEEP_REVERSAL","exchangeTimeZone":"UTC","referenceSession":"NEW_YORK","allowedSession":"LONDON","sessionWindows":[{"session":"LONDON","timeZone":"Europe/London","openMinute":480,"closeMinute":990},{"session":"NEW_YORK","timeZone":"America/New_York","openMinute":480,"closeMinute":1020}],"rejectionCloseInside":true,"stopBufferBps":2,"targetPolicy":"OPPOSITE_REFERENCE_LEVEL","feeBps":1,"slippageBps":2,"minimumSampleSize":30}},
  {"strategy_key":"new-york-prior-asia-sweep","version":1,"name":"New York / Prior Asia Sweep Reversal","market":"XAUUSD","timeframe":"5m","setup_type":"SESSION_SWEEP_REVERSAL","definition_hash":"50e039cdd7ffe62eadab5d0523682e31b73938d5b927ee37897b02425f58759f","definition":{"strategyId":"new-york-prior-asia-sweep","version":1,"name":"New York / Prior Asia Sweep Reversal","market":"XAUUSD","timeframe":"5m","setupType":"SESSION_SWEEP_REVERSAL","exchangeTimeZone":"UTC","referenceSession":"ASIA","allowedSession":"NEW_YORK","sessionWindows":[{"session":"ASIA","timeZone":"Asia/Tokyo","openMinute":540,"closeMinute":1020},{"session":"NEW_YORK","timeZone":"America/New_York","openMinute":480,"closeMinute":1020}],"rejectionCloseInside":true,"stopBufferBps":2,"targetPolicy":"OPPOSITE_REFERENCE_LEVEL","feeBps":1,"slippageBps":2,"minimumSampleSize":30}}
]
$strategies$::jsonb) as item
on conflict (strategy_key, version) do nothing;

comment on table public.strategy_definitions is
  'Immutable strategy definitions. Presence in the research catalog does not imply validated profitability.';
