create table public.trade_proposals(
 id uuid primary key default gen_random_uuid(),proposal_key text not null unique,proposal_version text not null,asset_id uuid not null references public.assets(id),source_type text not null,source_id text not null,
 instrument_id text,side text not null check(side in('BUY','SELL')),order_type text not null check(order_type in('MARKET','LIMIT')),quote_amount_sek numeric,quantity numeric,reference_price numeric,limit_price numeric,stop_price numeric,target_price numeric,max_slippage_bps integer,
 information_cutoff_at timestamptz not null,available_at timestamptz not null,expires_at timestamptz not null,meta_ready boolean,directional_support text not null check(directional_support in('BULLISH','BEARISH','UNKNOWN')),critical_safety text not null check(critical_safety in('PASS','FAIL','UNKNOWN')),liquidity_status text not null check(liquidity_status in('PASS','FAIL','UNKNOWN')),risk_status text not null check(risk_status in('PASS','FAIL','UNKNOWN')),data_age_ms integer,evidence_refs jsonb not null,input_hash text not null,created_at timestamptz not null default now(),check(available_at<=information_cutoff_at)
);
create table public.trade_eligibility_evaluations(
 id uuid primary key default gen_random_uuid(),evaluation_key text not null unique,proposal_id uuid not null references public.trade_proposals(id),policy_version text not null,decision text not null check(decision in('ELIGIBLE','REJECTED','DATA_BLOCKED')),requirements jsonb not null,requirements_failed jsonb not null,requirements_unknown jsonb not null,result_hash text not null,information_cutoff_at timestamptz not null,available_at timestamptz not null,execution_intent_id uuid references public.execution_intents(id),created_at timestamptz not null default now(),check(information_cutoff_at<=available_at)
);
create index trade_proposals_cutoff_idx on public.trade_proposals(information_cutoff_at desc);create index trade_eligibility_decision_idx on public.trade_eligibility_evaluations(decision,created_at desc);
create trigger trade_proposals_immutable before update or delete on public.trade_proposals for each row execute function public.prevent_execution_history_mutation();create trigger trade_eligibility_immutable before update or delete on public.trade_eligibility_evaluations for each row execute function public.prevent_execution_history_mutation();
alter table public.trade_proposals enable row level security;alter table public.trade_eligibility_evaluations enable row level security;create policy "public read trade proposals" on public.trade_proposals for select using(true);create policy "public read trade eligibility" on public.trade_eligibility_evaluations for select using(true);grant select on public.trade_proposals,public.trade_eligibility_evaluations to anon,authenticated;grant all on public.trade_proposals,public.trade_eligibility_evaluations to service_role;
alter table public.ingestion_runs drop constraint if exists ingestion_runs_job_kind_check;alter table public.ingestion_runs add constraint ingestion_runs_job_kind_check check(job_kind in('stock_quotes','wallet_transactions','wallet_discovery','crypto_market','wallet_pnl','wallet_evidence','fast_flow','wallet_clustering','jackpot_collector','jackpot_outcomes','market_events','paper_eligibility','paper_execution','paper_exits','paper_valuation','performance','fx','qualification','data_gap_closure','simulation','historical_replay','forecast_catalyst','expert_knowledge','baseline_forecast','forecast_performance','forecast_scheduler','forecast_outcomes','specialist_agents','news_ingestion','catalyst_classification','consensus','agent_performance','market_regime','meta_agent','meta_readiness','strategy_pattern_lab','candle_ingestion','ai_explanations','strategy_intelligence','execution','trade_eligibility'));
