create table public.execution_accounts(
 id uuid primary key default gen_random_uuid(),account_key text not null unique,provider text not null,provider_environment text not null check(provider_environment in('SHADOW','DEMO')),base_currency text not null default 'SEK',initial_cash_sek numeric(20,4),status text not null check(status in('ACTIVE','PAUSED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.account_state_observations(
 id uuid primary key default gen_random_uuid(),observation_key text not null unique,account_id uuid not null references public.execution_accounts(id),provider text not null,provider_environment text not null,balances jsonb not null,positions jsonb not null,total_equity_usd numeric(24,8),available_quote_usd numeric(24,8),data_status text not null check(data_status in('KNOWN','PARTIAL','UNKNOWN')),unknown_reasons jsonb not null default '[]',observed_at timestamptz not null,available_at timestamptz not null,source_reference text,payload_hash text not null,created_at timestamptz not null default now(),check(observed_at<=available_at)
);
create table public.risk_ledger_snapshots(
 id uuid primary key default gen_random_uuid(),snapshot_key text not null unique,account_id uuid not null references public.execution_accounts(id),ledger_version text not null,status text not null check(status in('KNOWN','UNKNOWN')),cash_sek numeric(20,4),open_positions integer,open_quantity numeric(30,12),average_cost_sek numeric(24,8),realized_pnl_sek numeric(20,4),fees_sek numeric(20,4),reserved_exposure_sek numeric(20,4),unknown_reasons jsonb not null default '[]',source_fill_ids jsonb not null default '[]',information_cutoff_at timestamptz not null,available_at timestamptz not null,result_hash text not null,created_at timestamptz not null default now(),check(information_cutoff_at<=available_at)
);
create index account_state_timeline_idx on public.account_state_observations(account_id,observed_at desc);create index risk_ledger_timeline_idx on public.risk_ledger_snapshots(account_id,information_cutoff_at desc);
create trigger account_state_observations_immutable before update or delete on public.account_state_observations for each row execute function public.prevent_execution_history_mutation();create trigger risk_ledger_snapshots_immutable before update or delete on public.risk_ledger_snapshots for each row execute function public.prevent_execution_history_mutation();
alter table public.execution_accounts enable row level security;alter table public.account_state_observations enable row level security;alter table public.risk_ledger_snapshots enable row level security;
create policy "public read execution accounts" on public.execution_accounts for select using(true);create policy "public read account observations" on public.account_state_observations for select using(true);create policy "public read risk ledger" on public.risk_ledger_snapshots for select using(true);
grant select on public.execution_accounts,public.account_state_observations,public.risk_ledger_snapshots to anon,authenticated;grant all on public.execution_accounts,public.account_state_observations,public.risk_ledger_snapshots to service_role;
insert into public.execution_accounts(account_key,provider,provider_environment,base_currency,initial_cash_sek,status) values('shadow-primary','shadow-execution','SHADOW','SEK',1000,'ACTIVE') on conflict(account_key)do nothing;
alter table public.ingestion_runs drop constraint if exists ingestion_runs_job_kind_check;alter table public.ingestion_runs add constraint ingestion_runs_job_kind_check check(job_kind in('stock_quotes','wallet_transactions','wallet_discovery','crypto_market','wallet_pnl','wallet_evidence','fast_flow','wallet_clustering','jackpot_collector','jackpot_outcomes','market_events','paper_eligibility','paper_execution','paper_exits','paper_valuation','performance','fx','qualification','data_gap_closure','simulation','historical_replay','forecast_catalyst','expert_knowledge','baseline_forecast','forecast_performance','forecast_scheduler','forecast_outcomes','specialist_agents','news_ingestion','catalyst_classification','consensus','agent_performance','market_regime','meta_agent','meta_readiness','strategy_pattern_lab','candle_ingestion','ai_explanations','strategy_intelligence','execution','trade_eligibility','account_state'));
