create table public.strategy_validation_window_plans(
 id uuid primary key default gen_random_uuid(),plan_key text not null unique,planner_version text not null,strategy_definition_id uuid not null references public.strategy_definitions(id),hypothesis_id uuid not null references public.strategy_hypotheses(id),phase text check(phase in('LEARNING','FROZEN','OUT_OF_SAMPLE','DEMO_VALIDATION')),status text not null check(status in('READY','BLOCKED','INSUFFICIENT_DATA','COMPLETED')),reason text,window_start timestamptz,window_end timestamptz,evaluation_run_ids jsonb not null,information_cutoff_at timestamptz not null,available_at timestamptz not null,plan_hash text not null,created_at timestamptz not null default now(),check(available_at<=information_cutoff_at),check(window_start is null or window_end is null or window_start<=window_end)
);
create table public.strategy_shadow_observations(
 id uuid primary key default gen_random_uuid(),observation_key text not null unique,tracking_version text not null,strategy_definition_id uuid not null references public.strategy_definitions(id),runtime_assessment_id uuid not null references public.strategy_runtime_assessments(id),mode text not null check(mode in('SHADOW','DEMO')),attribution_status text not null check(attribution_status in('KNOWN','UNKNOWN')),bucket_started_at timestamptz not null,bucket_ended_at timestamptz not null,information_cutoff_at timestamptz not null,available_at timestamptz not null,global_metrics jsonb not null,strategy_metrics jsonb not null,evidence_refs jsonb not null,result_hash text not null,created_at timestamptz not null default now(),check(bucket_started_at<=bucket_ended_at),check(available_at<=information_cutoff_at)
);
create index strategy_validation_window_plans_lookup_idx on public.strategy_validation_window_plans(strategy_definition_id,created_at desc);
create index strategy_shadow_observations_lookup_idx on public.strategy_shadow_observations(strategy_definition_id,bucket_ended_at desc);
create trigger strategy_validation_window_plans_immutable before update or delete on public.strategy_validation_window_plans for each row execute function public.prevent_strategy_lab_mutation();
create trigger strategy_shadow_observations_immutable before update or delete on public.strategy_shadow_observations for each row execute function public.prevent_strategy_lab_mutation();
alter table public.strategy_validation_window_plans enable row level security;alter table public.strategy_shadow_observations enable row level security;
create policy "public read validation window plans" on public.strategy_validation_window_plans for select using(true);create policy "public read shadow observations" on public.strategy_shadow_observations for select using(true);
grant select on public.strategy_validation_window_plans,public.strategy_shadow_observations to anon,authenticated;grant all on public.strategy_validation_window_plans,public.strategy_shadow_observations to service_role;
alter table public.scheduled_jobs drop constraint if exists scheduled_jobs_job_type_check;
alter table public.scheduled_jobs add constraint scheduled_jobs_job_type_check check(job_type in('STRATEGY_VALIDATION_WINDOWS','STRATEGY_SHADOW_TRACKING','WALLET_CLUSTERING','WALLET_EVIDENCE','WALLET_PNL','WALLET_PROMOTION','POOL_DISCOVERY','DATA_GAP_CLOSURE','QUALIFICATION','TRADE_PROPOSAL_PRODUCER','EXECUTION_PIPELINE','AI_EXPLANATION','CANDLE_INGESTION','STOCK_INGESTION','WALLET_INGESTION','WALLET_DISCOVERY','CRYPTO_MARKET','MARKET_EVENTS','FAST_FLOW','JACKPOT_COLLECTOR','BASELINE_FORECAST','FORECAST_OUTCOME','FORECAST_PERFORMANCE','NEWS_INGESTION','CATALYST_CLASSIFICATION','SPECIALIST_AGENTS','CONSENSUS','AGENT_PERFORMANCE','MARKET_REGIME','META_AGENT','META_READINESS'));
insert into public.scheduled_jobs(job_key,job_type,scheduler_version,interval_seconds,lease_seconds,status,next_run_at,rate_limit_budget,priority,enabled) values
('strategy-validation-windows-1h','STRATEGY_VALIDATION_WINDOWS','forecast-scheduler-v2.1',3600,300,'HEALTHY',now(),'{}',5,true),
('strategy-shadow-tracking-5m','STRATEGY_SHADOW_TRACKING','forecast-scheduler-v2.1',300,120,'HEALTHY',now(),'{}',6,true)
on conflict(job_key)do update set job_type=excluded.job_type,interval_seconds=excluded.interval_seconds,lease_seconds=excluded.lease_seconds,enabled=true,next_run_at=least(public.scheduled_jobs.next_run_at,now()),updated_at=now();
