create table public.strategy_promotion_evaluations(
 id uuid primary key default gen_random_uuid(),evaluation_key text not null unique,policy_version text not null,strategy_definition_id uuid not null references public.strategy_definitions(id),hypothesis_id uuid not null references public.strategy_hypotheses(id),from_state text not null,target_state text,decision text not null check(decision in('PROMOTE','HOLD','REVALIDATE','REJECT')),required_phase text,blockers jsonb not null,evidence_refs jsonb not null,information_cutoff_at timestamptz not null,available_at timestamptz not null,result_hash text not null,created_at timestamptz not null default now(),check(available_at<=information_cutoff_at)
);
create table public.strategy_lifecycle_revisions(
 id uuid primary key default gen_random_uuid(),revision_key text not null unique,policy_version text not null,strategy_definition_id uuid not null references public.strategy_definitions(id),hypothesis_id uuid not null references public.strategy_hypotheses(id),revision_number integer not null check(revision_number>0),state text not null check(state in('RESEARCH','FROZEN','OUT_OF_SAMPLE','DEMO_VALIDATION','APPROVED_SHADOW','LIVE_LIMITED','LIVE_APPROVED','REVALIDATION_REQUIRED','PAUSED','RETIRED','REJECTED')),previous_revision_id uuid references public.strategy_lifecycle_revisions(id),promotion_evaluation_id uuid references public.strategy_promotion_evaluations(id),evidence_refs jsonb not null,information_cutoff_at timestamptz not null,available_at timestamptz not null,result_hash text not null,created_at timestamptz not null default now(),unique(strategy_definition_id,hypothesis_id,revision_number),check(available_at<=information_cutoff_at)
);
create index strategy_promotion_lookup_idx on public.strategy_promotion_evaluations(strategy_definition_id,information_cutoff_at desc);create index strategy_lifecycle_lookup_idx on public.strategy_lifecycle_revisions(strategy_definition_id,hypothesis_id,revision_number desc);
create trigger strategy_promotion_evaluations_immutable before update or delete on public.strategy_promotion_evaluations for each row execute function public.prevent_strategy_lab_mutation();create trigger strategy_lifecycle_revisions_immutable before update or delete on public.strategy_lifecycle_revisions for each row execute function public.prevent_strategy_lab_mutation();
alter table public.strategy_promotion_evaluations enable row level security;alter table public.strategy_lifecycle_revisions enable row level security;create policy "public read strategy promotion" on public.strategy_promotion_evaluations for select using(true);create policy "public read strategy lifecycle" on public.strategy_lifecycle_revisions for select using(true);grant select on public.strategy_promotion_evaluations,public.strategy_lifecycle_revisions to anon,authenticated;grant all on public.strategy_promotion_evaluations,public.strategy_lifecycle_revisions to service_role;
alter table public.scheduled_jobs drop constraint if exists scheduled_jobs_job_type_check;
alter table public.scheduled_jobs add constraint scheduled_jobs_job_type_check check(job_type in('STRATEGY_VALIDATION_PROMOTION','STRATEGY_SIGNAL_PRODUCER','STRATEGY_SHADOW_EXECUTION','STRATEGY_VALIDATION_WINDOWS','STRATEGY_SHADOW_TRACKING','WALLET_CLUSTERING','WALLET_EVIDENCE','WALLET_PNL','WALLET_PROMOTION','POOL_DISCOVERY','DATA_GAP_CLOSURE','QUALIFICATION','TRADE_PROPOSAL_PRODUCER','EXECUTION_PIPELINE','AI_EXPLANATION','CANDLE_INGESTION','STOCK_INGESTION','WALLET_INGESTION','WALLET_DISCOVERY','CRYPTO_MARKET','MARKET_EVENTS','FAST_FLOW','JACKPOT_COLLECTOR','BASELINE_FORECAST','FORECAST_OUTCOME','FORECAST_PERFORMANCE','NEWS_INGESTION','CATALYST_CLASSIFICATION','SPECIALIST_AGENTS','CONSENSUS','AGENT_PERFORMANCE','MARKET_REGIME','META_AGENT','META_READINESS'));
insert into public.scheduled_jobs(job_key,job_type,scheduler_version,interval_seconds,lease_seconds,status,next_run_at,rate_limit_budget,priority,enabled)values('strategy-validation-promotion-15m','STRATEGY_VALIDATION_PROMOTION','forecast-scheduler-v2.1',900,120,'HEALTHY',now(),'{}',5,true)on conflict(job_key)do update set job_type=excluded.job_type,interval_seconds=excluded.interval_seconds,enabled=true,next_run_at=least(public.scheduled_jobs.next_run_at,now()),updated_at=now();
