import type { SupabaseClient } from "@supabase/supabase-js";
import { createExecutionIntent,evaluateExecutionSafety,type ExecutionIntentInput,type ExecutionLimits,type SafetyContext } from "@/domain/execution";
import { evaluateBridgeReadiness,EXECUTION_BRIDGE_POLICY_VERSION } from "@/domain/execution-bridge";
import { deterministicDigest } from "@/domain/events";
import { riskContextFromSnapshot } from "@/domain/risk-ledger";
import type { ExecutionProvider } from "./provider";
import { ExecutionService } from "./service";

const num=(v:unknown)=>v===null||v===undefined?null:Number(v),one=(v:any)=>Array.isArray(v)?v[0]:v;
export class ExecutionBridgeService{
 constructor(private db:SupabaseClient,private provider:ExecutionProvider){}
 async run(cutoffAt=new Date().toISOString(),limit=50){
  const control=await this.db.from("execution_controls").select("*").eq("control_key","global").single();if(control.error)throw control.error;if(control.data.live_execution_enabled)throw new Error("Live execution is forbidden");if(control.data.mode!==this.provider.mode)throw new Error("Execution provider mode mismatch");
  const evaluations=await this.db.from("trade_eligibility_evaluations").select("id,proposal_id,decision,available_at,trade_proposals!inner(*)").eq("decision","ELIGIBLE").lte("available_at",cutoffAt).order("created_at").limit(limit);if(evaluations.error)throw evaluations.error;
  const ids=(evaluations.data??[]).map(x=>x.id),existing=ids.length?await this.db.from("execution_bridge_attempts").select("eligibility_evaluation_id").in("eligibility_evaluation_id",ids).eq("bridge_policy_version",EXECUTION_BRIDGE_POLICY_VERSION):{data:[],error:null};if(existing.error)throw existing.error;const done=new Set((existing.data??[]).map(x=>x.eligibility_evaluation_id));
  const accountKey=this.provider.mode==="SHADOW"?"shadow-primary":`${this.provider.name}-primary`,account=await this.db.from("execution_accounts").select("id").eq("account_key",accountKey).maybeSingle();if(account.error)throw account.error;const health=await this.provider.health();let intentsCreated=0,safetyBlocked=0,dataBlocked=0,expired=0;
  for(const evaluation of evaluations.data??[]){if(done.has(evaluation.id))continue;const proposal=one((evaluation as any).trade_proposals),riskBase=this.db.from("risk_ledger_snapshots").select("*").eq("status","KNOWN").lte("available_at",cutoffAt),riskQuery=account.data?await riskBase.eq("account_id",account.data.id).order("information_cutoff_at",{ascending:false}).limit(1).maybeSingle():{data:null,error:null},risk=riskQuery.data;if(riskQuery.error)throw riskQuery.error;const observationBase=this.db.from("account_state_observations").select("*").lte("available_at",cutoffAt),observationQuery=account.data?await observationBase.eq("account_id",account.data.id).order("observed_at",{ascending:false}).limit(1).maybeSingle():{data:null,error:null};if(observationQuery.error)throw observationQuery.error;const observation=observationQuery.data;
   const readiness=evaluateBridgeReadiness({eligibilityDecision:evaluation.decision as "ELIGIBLE",proposalExpiresAt:proposal.expires_at,riskStatus:risk?.status??"UNKNOWN",riskAvailableAt:risk?.available_at??null,accountObservedAt:observation?.observed_at??null,cutoffAt,maxAccountAgeMs:Number(control.data.limits.maxDataAgeMs??15000)}),attemptKey=deterministicDigest({evaluationId:evaluation.id,policy:EXECUTION_BRIDGE_POLICY_VERSION});
   if(readiness.decision!=="READY"){const outcome=Date.parse(proposal.expires_at)<=Date.parse(cutoffAt)?"EXPIRED":"DATA_BLOCKED";await this.saveAttempt({attemptKey,evaluationId:evaluation.id,proposalId:proposal.id,riskId:risk?.id??null,observationId:observation?.id??null,intentId:null,outcome,requirements:readiness.requirements,safetyRequirements:[],cutoffAt,resultHash:readiness.resultHash});if(outcome==="EXPIRED")expired++;else dataBlocked++;continue}
   const riskContext=riskContextFromSnapshot({version:risk.ledger_version,accountId:risk.account_id,status:risk.status,cashSek:num(risk.cash_sek),openQuantity:Number(risk.open_quantity??0),averageCostSek:num(risk.average_cost_sek),realizedPnlSek:num(risk.realized_pnl_sek),feesSek:num(risk.fees_sek),reservedExposureSek:num(risk.reserved_exposure_sek),openPositions:Number(risk.open_positions??0),cutoffAt:risk.information_cutoff_at,unknownReasons:risk.unknown_reasons??[],snapshotKey:risk.snapshot_key,resultHash:risk.result_hash}),intentInput=this.intent(proposal,evaluation.id,risk.id,observation.id,cutoffAt),context:SafetyContext={mode:this.provider.mode,killSwitch:control.data.kill_switch,newOrdersEnabled:control.data.new_orders_enabled,liveExecutionEnabled:false,providerStatus:health.status,credentialsValid:health.credentialsValid,tradePermission:health.tradePermission,withdrawPermission:health.withdrawPermission,instrumentType:inferInstrumentType(proposal.instrument_id),leverage:1,openPositions:riskContext.openPositions,dailyLossSek:riskContext.dailyLossSek,totalExposureSek:riskContext.totalExposureSek,availableCashSek:riskContext.availableCashSek,dataAgeMs:num(proposal.data_age_ms),criticalSafety:proposal.critical_safety,liquidityStatus:proposal.liquidity_status,riskStatus:proposal.risk_status},limits=control.data.limits as ExecutionLimits,safety=evaluateExecutionSafety(createExecutionIntent(intentInput),context,limits);
   if(safety.decision!=="PASSED"){await this.saveAttempt({attemptKey,evaluationId:evaluation.id,proposalId:proposal.id,riskId:risk.id,observationId:observation.id,intentId:null,outcome:"SAFETY_BLOCKED",requirements:readiness.requirements,safetyRequirements:safety.requirements,cutoffAt,resultHash:safety.resultHash});safetyBlocked++;continue}
   const created=await new ExecutionService(this.db,this.provider).createAndEvaluate(intentInput,context,limits);await this.saveAttempt({attemptKey,evaluationId:evaluation.id,proposalId:proposal.id,riskId:risk.id,observationId:observation.id,intentId:created.intentId,outcome:"INTENT_CREATED",requirements:readiness.requirements,safetyRequirements:created.requirements,cutoffAt,resultHash:safety.resultHash});intentsCreated++;
  }
  return{considered:evaluations.data?.length??0,intentsCreated,safetyBlocked,dataBlocked,expired,policyVersion:EXECUTION_BRIDGE_POLICY_VERSION};
 }
 private intent(p:any,evaluationId:string,riskId:string,observationId:string,cutoffAt:string):ExecutionIntentInput{return{sourceType:"trade_eligibility",sourceId:evaluationId,assetId:p.asset_id,instrumentId:p.instrument_id,side:p.side,orderType:p.order_type,quoteAmountSek:Number(p.quote_amount_sek),quantity:num(p.quantity),limitPrice:num(p.limit_price),stopPrice:num(p.stop_price),targetPrice:num(p.target_price),maxSlippageBps:Number(p.max_slippage_bps),informationCutoffAt:cutoffAt,availableAt:cutoffAt,expiresAt:p.expires_at,evidenceRefs:[...(p.evidence_refs??[]),`eligibility:${evaluationId}`,`risk-ledger:${riskId}`,`account-state:${observationId}`],consensusVersion:null,forecastVersion:null,riskVersion:"risk-ledger-v1"}}
 private async saveAttempt(x:{attemptKey:string;evaluationId:string;proposalId:string;riskId:string|null;observationId:string|null;intentId:string|null;outcome:string;requirements:unknown;safetyRequirements:unknown;cutoffAt:string;resultHash:string}){const saved=await this.db.from("execution_bridge_attempts").upsert({attempt_key:x.attemptKey,eligibility_evaluation_id:x.evaluationId,proposal_id:x.proposalId,risk_snapshot_id:x.riskId,account_observation_id:x.observationId,execution_intent_id:x.intentId,bridge_policy_version:EXECUTION_BRIDGE_POLICY_VERSION,outcome:x.outcome,requirements:x.requirements,safety_requirements:x.safetyRequirements,information_cutoff_at:x.cutoffAt,available_at:new Date().toISOString(),result_hash:x.resultHash},{onConflict:"attempt_key",ignoreDuplicates:true});if(saved.error)throw saved.error}
}
function inferInstrumentType(instrument:string|null):"SPOT"|"MARGIN"|"FUTURES"|"UNKNOWN"{if(!instrument)return"UNKNOWN";if(instrument.includes("SWAP")||/\d{6}$/.test(instrument))return"FUTURES";return instrument.includes("-")?"SPOT":"UNKNOWN"}
