import { createHmac } from "node:crypto";
import type { ExecutionOrderRequest,ExecutionProvider,ProviderOrder } from "./provider";

type Fetcher=typeof fetch;type OkxEnvelope<T>={code:string;msg:string;data:T[]};
interface OkxOrder{ordId:string;clOrdId:string;state:string;accFillSz?:string;avgPx?:string;sCode?:string;sMsg?:string}
interface OkxConfig{perm:string;acctLv:string}
interface OkxBalance{totalEq?:string;details?:Array<{ccy:string;cashBal?:string;availBal?:string;eqUsd?:string}>}
interface OkxPosition{instId:string;pos?:string;avgPx?:string;upl?:string}
export interface OkxDemoCredentials{apiKey:string;secretKey:string;passphrase:string;baseUrl?:string}

export class OkxDemoExecutionProvider implements ExecutionProvider{
  readonly name="okx-demo";readonly mode="DEMO" as const;private baseUrl:string;
  constructor(private credentials:OkxDemoCredentials,private fetcher:Fetcher=fetch){this.baseUrl=validateBaseUrl(credentials.baseUrl??"https://eea.okx.com")}
  async health(){try{const config=(await this.request<OkxConfig>("GET","/api/v5/account/config"))[0];if(!config)return{status:"FAILED"as const,credentialsValid:false,tradePermission:false,withdrawPermission:null};const permissions=config.perm.split(",").map(x=>x.trim().toLowerCase()),tradePermission=permissions.includes("trade"),withdrawPermission=permissions.includes("withdraw"),spotMode=config.acctLv==="1";return{status:tradePermission&&!withdrawPermission&&spotMode?"HEALTHY"as const:"DEGRADED"as const,credentialsValid:true,tradePermission,withdrawPermission}}catch{return{status:"FAILED"as const,credentialsValid:false,tradePermission:false,withdrawPermission:null}}}
  async getAccountState(){const observedAt=new Date().toISOString(),balance=(await this.request<OkxBalance>("GET","/api/v5/account/balance"))[0],positions=await this.request<OkxPosition>("GET","/api/v5/account/positions");if(!balance)return{balances:[],positions:[],totalEquityUsd:null,availableQuoteUsd:null,status:"UNKNOWN"as const,unknownReasons:["OKX_BALANCE_MISSING"],observedAt,sourceReference:"/api/v5/account/balance"};const balances=(balance.details??[]).map(x=>({currency:x.ccy,total:Number(x.cashBal??0),available:x.availBal===undefined?null:Number(x.availBal)})),availableQuote=balances.filter(x=>["USD","USDT","USDC"].includes(x.currency)).reduce((sum,x)=>sum+(x.available??0),0);return{balances,positions:positions.map(x=>({instrumentId:x.instId,quantity:Number(x.pos??0),averagePrice:x.avgPx?Number(x.avgPx):null,unrealizedPnl:x.upl?Number(x.upl):null})),totalEquityUsd:balance.totalEq?Number(balance.totalEq):null,availableQuoteUsd:availableQuote,status:balance.totalEq?"KNOWN"as const:"PARTIAL"as const,unknownReasons:balance.totalEq?[]:["TOTAL_EQUITY_USD_MISSING"],observedAt,sourceReference:"/api/v5/account/balance"}}
  async placeOrder(order:ExecutionOrderRequest){if(order.quantity===null||order.quantity<=0)throw new Error("OKX demo requires an explicit positive base quantity");const body:Record<string,string>={instId:order.instrumentId,tdMode:"cash",clOrdId:order.clientOrderId,side:order.side.toLowerCase(),ordType:order.orderType.toLowerCase(),sz:String(order.quantity),tgtCcy:"base_ccy"};if(order.orderType==="LIMIT"){if(order.limitPrice===null||order.limitPrice<=0)throw new Error("Limit price required");body.px=String(order.limitPrice)}const response=(await this.request<OkxOrder>("POST","/api/v5/trade/order",body))[0];if(!response||response.sCode&&response.sCode!=="0")throw new Error(response?.sMsg||"OKX demo rejected order");return mapOrder(response,order.clientOrderId)}
  async getOrder(instrumentId:string,clientOrderId:string,providerOrderId:string|null){const query=`?instId=${encodeURIComponent(instrumentId)}&${providerOrderId?`ordId=${encodeURIComponent(providerOrderId)}`:`clOrdId=${encodeURIComponent(clientOrderId)}`}`,order=(await this.request<OkxOrder>("GET",`/api/v5/trade/order${query}`))[0];return order?mapOrder(order,clientOrderId):null}
  async cancelOrder(instrumentId:string,clientOrderId:string,providerOrderId:string|null):Promise<ProviderOrder>{const body:Record<string,string>={instId:instrumentId};if(providerOrderId)body.ordId=providerOrderId;else body.clOrdId=clientOrderId;const order=(await this.request<OkxOrder>("POST","/api/v5/trade/cancel-order",body))[0];if(!order||order.sCode&&order.sCode!=="0")throw new Error(order?.sMsg||"OKX demo cancel failed");return{...mapOrder(order,clientOrderId),state:"CANCELLED"}}
  private async request<T>(method:"GET"|"POST",path:string,body?:Record<string,string>){const timestamp=new Date().toISOString(),bodyText=body?JSON.stringify(body):"",signature=createHmac("sha256",this.credentials.secretKey).update(`${timestamp}${method}${path}${bodyText}`).digest("base64"),response=await this.fetcher(`${this.baseUrl}${path}`,{method,headers:{"Content-Type":"application/json","OK-ACCESS-KEY":this.credentials.apiKey,"OK-ACCESS-SIGN":signature,"OK-ACCESS-TIMESTAMP":timestamp,"OK-ACCESS-PASSPHRASE":this.credentials.passphrase,"x-simulated-trading":"1","expTime":String(Date.now()+5000)},body:bodyText||undefined});if(response.status===429)throw new Error("OKX_DEMO_RATE_LIMITED");const json=await response.json() as OkxEnvelope<T>;if(!response.ok||json.code!=="0")throw new Error(`OKX_DEMO_ERROR:${json.code}:${json.msg}`);return json.data}
}
function validateBaseUrl(value:string){const url=new URL(value),allowed=new Set(["https://eea.okx.com","https://openapi.okx.com","https://us.okx.com"]);if(url.pathname!=="/"||url.search||url.hash||!allowed.has(url.origin))throw new Error("Unapproved OKX demo base URL");return url.origin}
function mapOrder(order:OkxOrder,clientOrderId:string):ProviderOrder{const state=order.state==="filled"?"FILLED":order.state==="partially_filled"?"PARTIALLY_FILLED":order.state==="canceled"?"CANCELLED":order.state==="mmp_canceled"?"CANCELLED":order.state==="live"?"ACKNOWLEDGED":"ACKNOWLEDGED";return{providerOrderId:order.ordId,clientOrderId:order.clOrdId||clientOrderId,state,filledQuantity:Number(order.accFillSz??0),averagePrice:order.avgPx?Number(order.avgPx):null,observedAt:new Date().toISOString(),rawReference:order.ordId}}
