import type { SupabaseClient } from "@supabase/supabase-js";
import { assertExecutionTransition,createExecutionIntent,evaluateExecutionSafety,type ExecutionIntentInput,type ExecutionLimits,type SafetyContext,type ExecutionState } from "@/domain/execution";
import { deterministicDigest } from "@/domain/events";
import type { ExecutionProvider,ProviderOrder } from "./provider";

export class ExecutionService{
  constructor(private db:SupabaseClient,private provider:ExecutionProvider){}
  async createAndEvaluate(input:ExecutionIntentInput,context:SafetyContext,limits:ExecutionLimits){
    const intent=createExecutionIntent(input),insert=await this.db.from("execution_intents").upsert({intent_key:intent.intentKey,contract_version:intent.contractVersion,source_type:intent.sourceType,source_id:intent.sourceId,asset_id:intent.assetId,instrument_id:intent.instrumentId,side:intent.side,order_type:intent.orderType,quote_amount_sek:intent.quoteAmountSek,quantity:intent.quantity,limit_price:intent.limitPrice,stop_price:intent.stopPrice,target_price:intent.targetPrice,max_slippage_bps:intent.maxSlippageBps,information_cutoff_at:intent.informationCutoffAt,available_at:intent.availableAt,expires_at:intent.expiresAt,evidence_refs:intent.evidenceRefs,consensus_version:intent.consensusVersion,forecast_version:intent.forecastVersion,risk_version:intent.riskVersion,payload_hash:intent.payloadHash},{onConflict:"intent_key"}).select("id").single();
    if(insert.error)throw insert.error;const safety=evaluateExecutionSafety(intent,context,limits),evaluationKey=deterministicDigest({intentKey:intent.intentKey,resultHash:safety.resultHash});
    const evaluation=await this.db.from("execution_safety_evaluations").upsert({evaluation_key:evaluationKey,intent_id:insert.data.id,policy_version:safety.policyVersion,decision:safety.decision,requirements:safety.requirements,context,limits,result_hash:safety.resultHash,information_cutoff_at:intent.informationCutoffAt,available_at:new Date().toISOString()},{onConflict:"evaluation_key"}).select("id").single();if(evaluation.error)throw evaluation.error;
    const order=await this.ensureOrder(insert.data.id,evaluation.data.id,intent.intentKey,safety.decision==="PASSED"?"SAFETY_PASSED":"BLOCKED");return{intentId:insert.data.id,evaluationId:evaluation.data.id,orderId:order.id,decision:safety.decision,requirements:safety.requirements};
  }
  private async ensureOrder(intentId:string,evaluationId:string,intentKey:string,state:ExecutionState){const row=await this.db.from("execution_orders").upsert({intent_id:intentId,safety_evaluation_id:evaluationId,provider:this.provider.name,provider_environment:this.provider.mode,client_order_id:`ord_${deterministicDigest(intentKey).slice(0,28)}`,current_state:state},{onConflict:"intent_id"}).select("id,current_state,created_at").single();if(row.error)throw row.error;const eventKey=deterministicDigest({orderId:row.data.id,from:"PROPOSED",to:state,reason:"INITIAL_SAFETY_EVALUATION"}),event=await this.db.from("execution_order_events").upsert({event_key:eventKey,order_id:row.data.id,previous_state:"PROPOSED",next_state:state,reason:"INITIAL_SAFETY_EVALUATION",payload:{},occurred_at:row.data.created_at,available_at:new Date().toISOString()},{onConflict:"event_key",ignoreDuplicates:true});if(event.error)throw event.error;return row.data}
  async submitReady(limit=25){const{data:orders,error}=await this.db.from("execution_orders").select("id,current_state,client_order_id,provider_order_id,execution_intents!inner(instrument_id,side,order_type,quantity,quote_amount_sek,limit_price,expires_at)").eq("current_state","SAFETY_PASSED").order("created_at").limit(limit);if(error)throw error;let submitted=0;for(const row of orders??[]){const intent=one((row as any).execution_intents);if(!intent)continue;if(Date.parse(intent.expires_at)<=Date.now()){await this.transition(row.id,"SAFETY_PASSED","EXPIRED","INTENT_EXPIRED",null);continue}await this.transition(row.id,"SAFETY_PASSED","SUBMITTING","PROVIDER_SUBMISSION_STARTED",null);try{const providerOrder=await this.provider.placeOrder({clientOrderId:row.client_order_id,instrumentId:intent.instrument_id,side:intent.side,orderType:intent.order_type,quantity:intent.quantity,quoteAmountSek:Number(intent.quote_amount_sek),limitPrice:intent.limit_price===null?null:Number(intent.limit_price)});await this.db.from("execution_orders").update({provider_order_id:providerOrder.providerOrderId}).eq("id",row.id);await this.transition(row.id,"SUBMITTING","SUBMITTED","PROVIDER_ACCEPTED",providerOrder);if(providerOrder.state!=="ACKNOWLEDGED")await this.transition(row.id,"SUBMITTED",providerOrder.state,"PROVIDER_STATE",providerOrder);else await this.transition(row.id,"SUBMITTED","ACKNOWLEDGED","PROVIDER_ACKNOWLEDGED",providerOrder);submitted++}catch(error){await this.transition(row.id,"SUBMITTING","RECONCILIATION_REQUIRED",error instanceof Error?error.message:"Provider submission failed",null)}}return{submitted,considered:orders?.length??0}}
  async reconcile(limit=100){const startedAt=new Date().toISOString(),{data:orders,error}=await this.db.from("execution_orders").select("id,current_state,client_order_id,provider_order_id,execution_intents!inner(instrument_id)").in("current_state",["SUBMITTING","SUBMITTED","ACKNOWLEDGED","PARTIALLY_FILLED","RECONCILIATION_REQUIRED"]).limit(limit);if(error)throw error;let mismatches=0,recovered=0;for(const row of orders??[]){const intent=one((row as any).execution_intents);if(!intent){mismatches++;continue}const observed=await this.provider.getOrder(intent.instrument_id,row.client_order_id,row.provider_order_id);if(!observed){if(row.current_state==="SUBMITTING"){await this.transition(row.id,"SUBMITTING","RECONCILIATION_REQUIRED","PROVIDER_ORDER_NOT_FOUND",null);mismatches++}continue}const desired=observed.state;if(desired!==row.current_state){try{await this.transition(row.id,row.current_state as ExecutionState,desired,"RECONCILED_PROVIDER_STATE",observed);recovered++}catch{mismatches++}}}const finishedAt=new Date().toISOString(),runKey=deterministicDigest({provider:this.provider.name,mode:this.provider.mode,startedAt,finishedAt,checked:orders?.length??0,mismatches,recovered});const saved=await this.db.from("execution_reconciliation_runs").insert({run_key:runKey,provider:this.provider.name,provider_environment:this.provider.mode,started_at:startedAt,finished_at:finishedAt,orders_checked:orders?.length??0,mismatches,recovered,status:mismatches?"DEGRADED":"SUCCEEDED",details:{}});if(saved.error)throw saved.error;return{checked:orders?.length??0,mismatches,recovered}}
  private async transition(orderId:string,from:ExecutionState,to:ExecutionState,reason:string,providerOrder:ProviderOrder|null){assertExecutionTransition(from,to);const now=new Date().toISOString(),eventKey=deterministicDigest({orderId,from,to,reason,providerOrderId:providerOrder?.providerOrderId??null,observedAt:providerOrder?.observedAt??now});const event=await this.db.from("execution_order_events").upsert({event_key:eventKey,order_id:orderId,previous_state:from,next_state:to,reason,provider_reference:providerOrder?.rawReference??null,payload:providerOrder??{},occurred_at:providerOrder?.observedAt??now,available_at:now},{onConflict:"event_key",ignoreDuplicates:true});if(event.error)throw event.error;const update=await this.db.from("execution_orders").update({current_state:to,filled_quantity:providerOrder?.filledQuantity??0,average_price:providerOrder?.averagePrice??null,last_provider_observed_at:providerOrder?.observedAt??null,updated_at:now}).eq("id",orderId).eq("current_state",from).select("id");if(update.error)throw update.error;if(!update.data?.length)throw new Error("Concurrent execution transition rejected")}
}
function one<T>(value:T|T[]|null|undefined):T|null{return Array.isArray(value)?value[0]??null:value??null}
